// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package lan

import (
	"context"
	"reflect"

	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupConfig(ctx *pulumi.Context, args *LookupConfigArgs, opts ...pulumi.InvokeOption) (*LookupConfigResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupConfigResult
	err := ctx.Invoke("freebox:lan:getConfig", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupConfigArgs struct {
}

type LookupConfigResult struct {
	Ip          string `pulumi:"ip"`
	Mode        string `pulumi:"mode"`
	Name        string `pulumi:"name"`
	NameDns     string `pulumi:"nameDns"`
	NameMdns    string `pulumi:"nameMdns"`
	NameNetbios string `pulumi:"nameNetbios"`
}

func LookupConfigOutput(ctx *pulumi.Context, args LookupConfigOutputArgs, opts ...pulumi.InvokeOption) LookupConfigResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupConfigResultOutput, error) {
			args := v.(LookupConfigArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("freebox:lan:getConfig", args, LookupConfigResultOutput{}, options).(LookupConfigResultOutput), nil
		}).(LookupConfigResultOutput)
}

type LookupConfigOutputArgs struct {
}

func (LookupConfigOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupConfigArgs)(nil)).Elem()
}

type LookupConfigResultOutput struct{ *pulumi.OutputState }

func (LookupConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupConfigResult)(nil)).Elem()
}

func (o LookupConfigResultOutput) ToLookupConfigResultOutput() LookupConfigResultOutput {
	return o
}

func (o LookupConfigResultOutput) ToLookupConfigResultOutputWithContext(ctx context.Context) LookupConfigResultOutput {
	return o
}

func (o LookupConfigResultOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v LookupConfigResult) string { return v.Ip }).(pulumi.StringOutput)
}

func (o LookupConfigResultOutput) Mode() pulumi.StringOutput {
	return o.ApplyT(func(v LookupConfigResult) string { return v.Mode }).(pulumi.StringOutput)
}

func (o LookupConfigResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupConfigResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupConfigResultOutput) NameDns() pulumi.StringOutput {
	return o.ApplyT(func(v LookupConfigResult) string { return v.NameDns }).(pulumi.StringOutput)
}

func (o LookupConfigResultOutput) NameMdns() pulumi.StringOutput {
	return o.ApplyT(func(v LookupConfigResult) string { return v.NameMdns }).(pulumi.StringOutput)
}

func (o LookupConfigResultOutput) NameNetbios() pulumi.StringOutput {
	return o.ApplyT(func(v LookupConfigResult) string { return v.NameNetbios }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupConfigResultOutput{})
}
