// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package lan

import (
	"context"
	"reflect"

	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox"
	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetInterfaces(ctx *pulumi.Context, args *GetInterfacesArgs, opts ...pulumi.InvokeOption) (*GetInterfacesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetInterfacesResult
	err := ctx.Invoke("freebox:lan:getInterfaces", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetInterfacesArgs struct {
}

type GetInterfacesResult struct {
	Interfaces []freebox.LanInterfaceInfo `pulumi:"interfaces"`
}

func GetInterfacesOutput(ctx *pulumi.Context, args GetInterfacesOutputArgs, opts ...pulumi.InvokeOption) GetInterfacesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetInterfacesResultOutput, error) {
			args := v.(GetInterfacesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("freebox:lan:getInterfaces", args, GetInterfacesResultOutput{}, options).(GetInterfacesResultOutput), nil
		}).(GetInterfacesResultOutput)
}

type GetInterfacesOutputArgs struct {
}

func (GetInterfacesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInterfacesArgs)(nil)).Elem()
}

type GetInterfacesResultOutput struct{ *pulumi.OutputState }

func (GetInterfacesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInterfacesResult)(nil)).Elem()
}

func (o GetInterfacesResultOutput) ToGetInterfacesResultOutput() GetInterfacesResultOutput {
	return o
}

func (o GetInterfacesResultOutput) ToGetInterfacesResultOutputWithContext(ctx context.Context) GetInterfacesResultOutput {
	return o
}

func (o GetInterfacesResultOutput) Interfaces() freebox.LanInterfaceInfoArrayOutput {
	return o.ApplyT(func(v GetInterfacesResult) []freebox.LanInterfaceInfo { return v.Interfaces }).(freebox.LanInterfaceInfoArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetInterfacesResultOutput{})
}
