// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package lan

import (
	"context"
	"reflect"

	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox"
	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetInterfaceHost(ctx *pulumi.Context, args *GetInterfaceHostArgs, opts ...pulumi.InvokeOption) (*GetInterfaceHostResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetInterfaceHostResult
	err := ctx.Invoke("freebox:lan:getInterfaceHost", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetInterfaceHostArgs struct {
	HostId    string `pulumi:"hostId"`
	Interface string `pulumi:"interface"`
}

type GetInterfaceHostResult struct {
	HostId    string                 `pulumi:"hostId"`
	Interface string                 `pulumi:"interface"`
	L2ident   freebox.LanHostL2Ident `pulumi:"l2ident"`
}

func GetInterfaceHostOutput(ctx *pulumi.Context, args GetInterfaceHostOutputArgs, opts ...pulumi.InvokeOption) GetInterfaceHostResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetInterfaceHostResultOutput, error) {
			args := v.(GetInterfaceHostArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("freebox:lan:getInterfaceHost", args, GetInterfaceHostResultOutput{}, options).(GetInterfaceHostResultOutput), nil
		}).(GetInterfaceHostResultOutput)
}

type GetInterfaceHostOutputArgs struct {
	HostId    pulumi.StringInput `pulumi:"hostId"`
	Interface pulumi.StringInput `pulumi:"interface"`
}

func (GetInterfaceHostOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInterfaceHostArgs)(nil)).Elem()
}

type GetInterfaceHostResultOutput struct{ *pulumi.OutputState }

func (GetInterfaceHostResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInterfaceHostResult)(nil)).Elem()
}

func (o GetInterfaceHostResultOutput) ToGetInterfaceHostResultOutput() GetInterfaceHostResultOutput {
	return o
}

func (o GetInterfaceHostResultOutput) ToGetInterfaceHostResultOutputWithContext(ctx context.Context) GetInterfaceHostResultOutput {
	return o
}

func (o GetInterfaceHostResultOutput) HostId() pulumi.StringOutput {
	return o.ApplyT(func(v GetInterfaceHostResult) string { return v.HostId }).(pulumi.StringOutput)
}

func (o GetInterfaceHostResultOutput) Interface() pulumi.StringOutput {
	return o.ApplyT(func(v GetInterfaceHostResult) string { return v.Interface }).(pulumi.StringOutput)
}

func (o GetInterfaceHostResultOutput) L2ident() freebox.LanHostL2IdentOutput {
	return o.ApplyT(func(v GetInterfaceHostResult) freebox.LanHostL2Ident { return v.L2ident }).(freebox.LanHostL2IdentOutput)
}

func init() {
	pulumi.RegisterOutputType(GetInterfaceHostResultOutput{})
}
