// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package lan

import (
	"context"
	"reflect"

	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox"
	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetInterfaceHosts(ctx *pulumi.Context, args *GetInterfaceHostsArgs, opts ...pulumi.InvokeOption) (*GetInterfaceHostsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetInterfaceHostsResult
	err := ctx.Invoke("freebox:lan:getInterfaceHosts", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetInterfaceHostsArgs struct {
	Interface string `pulumi:"interface"`
}

type GetInterfaceHostsResult struct {
	Hosts []freebox.LanInterfaceHostRef `pulumi:"hosts"`
}

func GetInterfaceHostsOutput(ctx *pulumi.Context, args GetInterfaceHostsOutputArgs, opts ...pulumi.InvokeOption) GetInterfaceHostsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetInterfaceHostsResultOutput, error) {
			args := v.(GetInterfaceHostsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("freebox:lan:getInterfaceHosts", args, GetInterfaceHostsResultOutput{}, options).(GetInterfaceHostsResultOutput), nil
		}).(GetInterfaceHostsResultOutput)
}

type GetInterfaceHostsOutputArgs struct {
	Interface pulumi.StringInput `pulumi:"interface"`
}

func (GetInterfaceHostsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInterfaceHostsArgs)(nil)).Elem()
}

type GetInterfaceHostsResultOutput struct{ *pulumi.OutputState }

func (GetInterfaceHostsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInterfaceHostsResult)(nil)).Elem()
}

func (o GetInterfaceHostsResultOutput) ToGetInterfaceHostsResultOutput() GetInterfaceHostsResultOutput {
	return o
}

func (o GetInterfaceHostsResultOutput) ToGetInterfaceHostsResultOutputWithContext(ctx context.Context) GetInterfaceHostsResultOutput {
	return o
}

func (o GetInterfaceHostsResultOutput) Hosts() freebox.LanInterfaceHostRefArrayOutput {
	return o.ApplyT(func(v GetInterfaceHostsResult) []freebox.LanInterfaceHostRef { return v.Hosts }).(freebox.LanInterfaceHostRefArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetInterfaceHostsResultOutput{})
}
