// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package freebox

import (
	"context"
	"reflect"

	"errors"
	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Configuration for the Freebox provider.
type Provider struct {
	pulumi.ProviderResourceState

	// The version of the API to use (default: latest).
	ApiVersion pulumi.StringPtrOutput `pulumi:"apiVersion"`
	// The ID of the application for Freebox API authentication.
	AppId pulumi.StringOutput `pulumi:"appId"`
	// The address of the Freebox (default: http://mafreebox.freebox.fr).
	Endpoint pulumi.StringPtrOutput `pulumi:"endpoint"`
	// The private token for Freebox API authentication.
	Token pulumi.StringOutput `pulumi:"token"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AppId == nil {
		return nil, errors.New("invalid value for required argument 'AppId'")
	}
	if args.Token == nil {
		return nil, errors.New("invalid value for required argument 'Token'")
	}
	if args.AppId != nil {
		args.AppId = pulumi.ToSecret(args.AppId).(pulumi.StringInput)
	}
	if args.Token != nil {
		args.Token = pulumi.ToSecret(args.Token).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"appId",
		"token",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:freebox", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// The version of the API to use (default: latest).
	ApiVersion *string `pulumi:"apiVersion"`
	// The ID of the application for Freebox API authentication.
	AppId string `pulumi:"appId"`
	// The address of the Freebox (default: http://mafreebox.freebox.fr).
	Endpoint *string `pulumi:"endpoint"`
	// The private token for Freebox API authentication.
	Token string `pulumi:"token"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// The version of the API to use (default: latest).
	ApiVersion pulumi.StringPtrInput
	// The ID of the application for Freebox API authentication.
	AppId pulumi.StringInput
	// The address of the Freebox (default: http://mafreebox.freebox.fr).
	Endpoint pulumi.StringPtrInput
	// The private token for Freebox API authentication.
	Token pulumi.StringInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// The version of the API to use (default: latest).
func (o ProviderOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ApiVersion }).(pulumi.StringPtrOutput)
}

// The ID of the application for Freebox API authentication.
func (o ProviderOutput) AppId() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.AppId }).(pulumi.StringOutput)
}

// The address of the Freebox (default: http://mafreebox.freebox.fr).
func (o ProviderOutput) Endpoint() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Endpoint }).(pulumi.StringPtrOutput)
}

// The private token for Freebox API authentication.
func (o ProviderOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.Token }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
