// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package freebox

import (
	"context"
	"reflect"

	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type DhcpLeaseInfo struct {
	Comment  string `pulumi:"comment"`
	Hostname string `pulumi:"hostname"`
	Ip       string `pulumi:"ip"`
	LeaseId  string `pulumi:"leaseId"`
	Mac      string `pulumi:"mac"`
}

type DhcpLeaseInfoOutput struct{ *pulumi.OutputState }

func (DhcpLeaseInfoOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DhcpLeaseInfo)(nil)).Elem()
}

func (o DhcpLeaseInfoOutput) ToDhcpLeaseInfoOutput() DhcpLeaseInfoOutput {
	return o
}

func (o DhcpLeaseInfoOutput) ToDhcpLeaseInfoOutputWithContext(ctx context.Context) DhcpLeaseInfoOutput {
	return o
}

func (o DhcpLeaseInfoOutput) Comment() pulumi.StringOutput {
	return o.ApplyT(func(v DhcpLeaseInfo) string { return v.Comment }).(pulumi.StringOutput)
}

func (o DhcpLeaseInfoOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v DhcpLeaseInfo) string { return v.Hostname }).(pulumi.StringOutput)
}

func (o DhcpLeaseInfoOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v DhcpLeaseInfo) string { return v.Ip }).(pulumi.StringOutput)
}

func (o DhcpLeaseInfoOutput) LeaseId() pulumi.StringOutput {
	return o.ApplyT(func(v DhcpLeaseInfo) string { return v.LeaseId }).(pulumi.StringOutput)
}

func (o DhcpLeaseInfoOutput) Mac() pulumi.StringOutput {
	return o.ApplyT(func(v DhcpLeaseInfo) string { return v.Mac }).(pulumi.StringOutput)
}

type DhcpLeaseInfoArrayOutput struct{ *pulumi.OutputState }

func (DhcpLeaseInfoArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DhcpLeaseInfo)(nil)).Elem()
}

func (o DhcpLeaseInfoArrayOutput) ToDhcpLeaseInfoArrayOutput() DhcpLeaseInfoArrayOutput {
	return o
}

func (o DhcpLeaseInfoArrayOutput) ToDhcpLeaseInfoArrayOutputWithContext(ctx context.Context) DhcpLeaseInfoArrayOutput {
	return o
}

func (o DhcpLeaseInfoArrayOutput) Index(i pulumi.IntInput) DhcpLeaseInfoOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) DhcpLeaseInfo {
		return vs[0].([]DhcpLeaseInfo)[vs[1].(int)]
	}).(DhcpLeaseInfoOutput)
}

type LanHost struct {
	Active               bool                    `pulumi:"active"`
	DefaultName          string                  `pulumi:"defaultName"`
	FirstActivitySeconds *float64                `pulumi:"firstActivitySeconds"`
	HostId               string                  `pulumi:"hostId"`
	HostType             string                  `pulumi:"hostType"`
	Interface            string                  `pulumi:"interface"`
	L2ident              LanHostL2Ident          `pulumi:"l2ident"`
	L3connectivities     []LanHostL3Connectivity `pulumi:"l3connectivities"`
	Names                []LanHostName           `pulumi:"names"`
	NetworkControl       *LanHostNetworkControl  `pulumi:"networkControl"`
	Persistent           bool                    `pulumi:"persistent"`
	PrimaryName          string                  `pulumi:"primaryName"`
	PrimaryNameManual    bool                    `pulumi:"primaryNameManual"`
	Reachable            bool                    `pulumi:"reachable"`
	VendorName           string                  `pulumi:"vendorName"`
}

type LanHostOutput struct{ *pulumi.OutputState }

func (LanHostOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LanHost)(nil)).Elem()
}

func (o LanHostOutput) ToLanHostOutput() LanHostOutput {
	return o
}

func (o LanHostOutput) ToLanHostOutputWithContext(ctx context.Context) LanHostOutput {
	return o
}

func (o LanHostOutput) Active() pulumi.BoolOutput {
	return o.ApplyT(func(v LanHost) bool { return v.Active }).(pulumi.BoolOutput)
}

func (o LanHostOutput) DefaultName() pulumi.StringOutput {
	return o.ApplyT(func(v LanHost) string { return v.DefaultName }).(pulumi.StringOutput)
}

func (o LanHostOutput) FirstActivitySeconds() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v LanHost) *float64 { return v.FirstActivitySeconds }).(pulumi.Float64PtrOutput)
}

func (o LanHostOutput) HostId() pulumi.StringOutput {
	return o.ApplyT(func(v LanHost) string { return v.HostId }).(pulumi.StringOutput)
}

func (o LanHostOutput) HostType() pulumi.StringOutput {
	return o.ApplyT(func(v LanHost) string { return v.HostType }).(pulumi.StringOutput)
}

func (o LanHostOutput) Interface() pulumi.StringOutput {
	return o.ApplyT(func(v LanHost) string { return v.Interface }).(pulumi.StringOutput)
}

func (o LanHostOutput) L2ident() LanHostL2IdentOutput {
	return o.ApplyT(func(v LanHost) LanHostL2Ident { return v.L2ident }).(LanHostL2IdentOutput)
}

func (o LanHostOutput) L3connectivities() LanHostL3ConnectivityArrayOutput {
	return o.ApplyT(func(v LanHost) []LanHostL3Connectivity { return v.L3connectivities }).(LanHostL3ConnectivityArrayOutput)
}

func (o LanHostOutput) Names() LanHostNameArrayOutput {
	return o.ApplyT(func(v LanHost) []LanHostName { return v.Names }).(LanHostNameArrayOutput)
}

func (o LanHostOutput) NetworkControl() LanHostNetworkControlPtrOutput {
	return o.ApplyT(func(v LanHost) *LanHostNetworkControl { return v.NetworkControl }).(LanHostNetworkControlPtrOutput)
}

func (o LanHostOutput) Persistent() pulumi.BoolOutput {
	return o.ApplyT(func(v LanHost) bool { return v.Persistent }).(pulumi.BoolOutput)
}

func (o LanHostOutput) PrimaryName() pulumi.StringOutput {
	return o.ApplyT(func(v LanHost) string { return v.PrimaryName }).(pulumi.StringOutput)
}

func (o LanHostOutput) PrimaryNameManual() pulumi.BoolOutput {
	return o.ApplyT(func(v LanHost) bool { return v.PrimaryNameManual }).(pulumi.BoolOutput)
}

func (o LanHostOutput) Reachable() pulumi.BoolOutput {
	return o.ApplyT(func(v LanHost) bool { return v.Reachable }).(pulumi.BoolOutput)
}

func (o LanHostOutput) VendorName() pulumi.StringOutput {
	return o.ApplyT(func(v LanHost) string { return v.VendorName }).(pulumi.StringOutput)
}

type LanHostPtrOutput struct{ *pulumi.OutputState }

func (LanHostPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LanHost)(nil)).Elem()
}

func (o LanHostPtrOutput) ToLanHostPtrOutput() LanHostPtrOutput {
	return o
}

func (o LanHostPtrOutput) ToLanHostPtrOutputWithContext(ctx context.Context) LanHostPtrOutput {
	return o
}

func (o LanHostPtrOutput) Elem() LanHostOutput {
	return o.ApplyT(func(v *LanHost) LanHost {
		if v != nil {
			return *v
		}
		var ret LanHost
		return ret
	}).(LanHostOutput)
}

func (o LanHostPtrOutput) Active() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *LanHost) *bool {
		if v == nil {
			return nil
		}
		return &v.Active
	}).(pulumi.BoolPtrOutput)
}

func (o LanHostPtrOutput) DefaultName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LanHost) *string {
		if v == nil {
			return nil
		}
		return &v.DefaultName
	}).(pulumi.StringPtrOutput)
}

func (o LanHostPtrOutput) FirstActivitySeconds() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *LanHost) *float64 {
		if v == nil {
			return nil
		}
		return v.FirstActivitySeconds
	}).(pulumi.Float64PtrOutput)
}

func (o LanHostPtrOutput) HostId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LanHost) *string {
		if v == nil {
			return nil
		}
		return &v.HostId
	}).(pulumi.StringPtrOutput)
}

func (o LanHostPtrOutput) HostType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LanHost) *string {
		if v == nil {
			return nil
		}
		return &v.HostType
	}).(pulumi.StringPtrOutput)
}

func (o LanHostPtrOutput) Interface() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LanHost) *string {
		if v == nil {
			return nil
		}
		return &v.Interface
	}).(pulumi.StringPtrOutput)
}

func (o LanHostPtrOutput) L2ident() LanHostL2IdentPtrOutput {
	return o.ApplyT(func(v *LanHost) *LanHostL2Ident {
		if v == nil {
			return nil
		}
		return &v.L2ident
	}).(LanHostL2IdentPtrOutput)
}

func (o LanHostPtrOutput) L3connectivities() LanHostL3ConnectivityArrayOutput {
	return o.ApplyT(func(v *LanHost) []LanHostL3Connectivity {
		if v == nil {
			return nil
		}
		return v.L3connectivities
	}).(LanHostL3ConnectivityArrayOutput)
}

func (o LanHostPtrOutput) Names() LanHostNameArrayOutput {
	return o.ApplyT(func(v *LanHost) []LanHostName {
		if v == nil {
			return nil
		}
		return v.Names
	}).(LanHostNameArrayOutput)
}

func (o LanHostPtrOutput) NetworkControl() LanHostNetworkControlPtrOutput {
	return o.ApplyT(func(v *LanHost) *LanHostNetworkControl {
		if v == nil {
			return nil
		}
		return v.NetworkControl
	}).(LanHostNetworkControlPtrOutput)
}

func (o LanHostPtrOutput) Persistent() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *LanHost) *bool {
		if v == nil {
			return nil
		}
		return &v.Persistent
	}).(pulumi.BoolPtrOutput)
}

func (o LanHostPtrOutput) PrimaryName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LanHost) *string {
		if v == nil {
			return nil
		}
		return &v.PrimaryName
	}).(pulumi.StringPtrOutput)
}

func (o LanHostPtrOutput) PrimaryNameManual() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *LanHost) *bool {
		if v == nil {
			return nil
		}
		return &v.PrimaryNameManual
	}).(pulumi.BoolPtrOutput)
}

func (o LanHostPtrOutput) Reachable() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *LanHost) *bool {
		if v == nil {
			return nil
		}
		return &v.Reachable
	}).(pulumi.BoolPtrOutput)
}

func (o LanHostPtrOutput) VendorName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LanHost) *string {
		if v == nil {
			return nil
		}
		return &v.VendorName
	}).(pulumi.StringPtrOutput)
}

type LanHostL2Ident struct {
	L2Id string `pulumi:"l2Id"`
	Type string `pulumi:"type"`
}

type LanHostL2IdentOutput struct{ *pulumi.OutputState }

func (LanHostL2IdentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LanHostL2Ident)(nil)).Elem()
}

func (o LanHostL2IdentOutput) ToLanHostL2IdentOutput() LanHostL2IdentOutput {
	return o
}

func (o LanHostL2IdentOutput) ToLanHostL2IdentOutputWithContext(ctx context.Context) LanHostL2IdentOutput {
	return o
}

func (o LanHostL2IdentOutput) L2Id() pulumi.StringOutput {
	return o.ApplyT(func(v LanHostL2Ident) string { return v.L2Id }).(pulumi.StringOutput)
}

func (o LanHostL2IdentOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LanHostL2Ident) string { return v.Type }).(pulumi.StringOutput)
}

type LanHostL2IdentPtrOutput struct{ *pulumi.OutputState }

func (LanHostL2IdentPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LanHostL2Ident)(nil)).Elem()
}

func (o LanHostL2IdentPtrOutput) ToLanHostL2IdentPtrOutput() LanHostL2IdentPtrOutput {
	return o
}

func (o LanHostL2IdentPtrOutput) ToLanHostL2IdentPtrOutputWithContext(ctx context.Context) LanHostL2IdentPtrOutput {
	return o
}

func (o LanHostL2IdentPtrOutput) Elem() LanHostL2IdentOutput {
	return o.ApplyT(func(v *LanHostL2Ident) LanHostL2Ident {
		if v != nil {
			return *v
		}
		var ret LanHostL2Ident
		return ret
	}).(LanHostL2IdentOutput)
}

func (o LanHostL2IdentPtrOutput) L2Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LanHostL2Ident) *string {
		if v == nil {
			return nil
		}
		return &v.L2Id
	}).(pulumi.StringPtrOutput)
}

func (o LanHostL2IdentPtrOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LanHostL2Ident) *string {
		if v == nil {
			return nil
		}
		return &v.Type
	}).(pulumi.StringPtrOutput)
}

type LanHostL3Connectivity struct {
	Active    bool   `pulumi:"active"`
	Address   string `pulumi:"address"`
	Reachable bool   `pulumi:"reachable"`
	Type      string `pulumi:"type"`
}

type LanHostL3ConnectivityOutput struct{ *pulumi.OutputState }

func (LanHostL3ConnectivityOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LanHostL3Connectivity)(nil)).Elem()
}

func (o LanHostL3ConnectivityOutput) ToLanHostL3ConnectivityOutput() LanHostL3ConnectivityOutput {
	return o
}

func (o LanHostL3ConnectivityOutput) ToLanHostL3ConnectivityOutputWithContext(ctx context.Context) LanHostL3ConnectivityOutput {
	return o
}

func (o LanHostL3ConnectivityOutput) Active() pulumi.BoolOutput {
	return o.ApplyT(func(v LanHostL3Connectivity) bool { return v.Active }).(pulumi.BoolOutput)
}

func (o LanHostL3ConnectivityOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v LanHostL3Connectivity) string { return v.Address }).(pulumi.StringOutput)
}

func (o LanHostL3ConnectivityOutput) Reachable() pulumi.BoolOutput {
	return o.ApplyT(func(v LanHostL3Connectivity) bool { return v.Reachable }).(pulumi.BoolOutput)
}

func (o LanHostL3ConnectivityOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LanHostL3Connectivity) string { return v.Type }).(pulumi.StringOutput)
}

type LanHostL3ConnectivityArrayOutput struct{ *pulumi.OutputState }

func (LanHostL3ConnectivityArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]LanHostL3Connectivity)(nil)).Elem()
}

func (o LanHostL3ConnectivityArrayOutput) ToLanHostL3ConnectivityArrayOutput() LanHostL3ConnectivityArrayOutput {
	return o
}

func (o LanHostL3ConnectivityArrayOutput) ToLanHostL3ConnectivityArrayOutputWithContext(ctx context.Context) LanHostL3ConnectivityArrayOutput {
	return o
}

func (o LanHostL3ConnectivityArrayOutput) Index(i pulumi.IntInput) LanHostL3ConnectivityOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) LanHostL3Connectivity {
		return vs[0].([]LanHostL3Connectivity)[vs[1].(int)]
	}).(LanHostL3ConnectivityOutput)
}

type LanHostName struct {
	Name   string `pulumi:"name"`
	Source string `pulumi:"source"`
}

type LanHostNameOutput struct{ *pulumi.OutputState }

func (LanHostNameOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LanHostName)(nil)).Elem()
}

func (o LanHostNameOutput) ToLanHostNameOutput() LanHostNameOutput {
	return o
}

func (o LanHostNameOutput) ToLanHostNameOutputWithContext(ctx context.Context) LanHostNameOutput {
	return o
}

func (o LanHostNameOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LanHostName) string { return v.Name }).(pulumi.StringOutput)
}

func (o LanHostNameOutput) Source() pulumi.StringOutput {
	return o.ApplyT(func(v LanHostName) string { return v.Source }).(pulumi.StringOutput)
}

type LanHostNameArrayOutput struct{ *pulumi.OutputState }

func (LanHostNameArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]LanHostName)(nil)).Elem()
}

func (o LanHostNameArrayOutput) ToLanHostNameArrayOutput() LanHostNameArrayOutput {
	return o
}

func (o LanHostNameArrayOutput) ToLanHostNameArrayOutputWithContext(ctx context.Context) LanHostNameArrayOutput {
	return o
}

func (o LanHostNameArrayOutput) Index(i pulumi.IntInput) LanHostNameOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) LanHostName {
		return vs[0].([]LanHostName)[vs[1].(int)]
	}).(LanHostNameOutput)
}

type LanHostNetworkControl struct {
	CurrentMode string `pulumi:"currentMode"`
	Name        string `pulumi:"name"`
	ProfileId   int    `pulumi:"profileId"`
}

type LanHostNetworkControlOutput struct{ *pulumi.OutputState }

func (LanHostNetworkControlOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LanHostNetworkControl)(nil)).Elem()
}

func (o LanHostNetworkControlOutput) ToLanHostNetworkControlOutput() LanHostNetworkControlOutput {
	return o
}

func (o LanHostNetworkControlOutput) ToLanHostNetworkControlOutputWithContext(ctx context.Context) LanHostNetworkControlOutput {
	return o
}

func (o LanHostNetworkControlOutput) CurrentMode() pulumi.StringOutput {
	return o.ApplyT(func(v LanHostNetworkControl) string { return v.CurrentMode }).(pulumi.StringOutput)
}

func (o LanHostNetworkControlOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LanHostNetworkControl) string { return v.Name }).(pulumi.StringOutput)
}

func (o LanHostNetworkControlOutput) ProfileId() pulumi.IntOutput {
	return o.ApplyT(func(v LanHostNetworkControl) int { return v.ProfileId }).(pulumi.IntOutput)
}

type LanHostNetworkControlPtrOutput struct{ *pulumi.OutputState }

func (LanHostNetworkControlPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LanHostNetworkControl)(nil)).Elem()
}

func (o LanHostNetworkControlPtrOutput) ToLanHostNetworkControlPtrOutput() LanHostNetworkControlPtrOutput {
	return o
}

func (o LanHostNetworkControlPtrOutput) ToLanHostNetworkControlPtrOutputWithContext(ctx context.Context) LanHostNetworkControlPtrOutput {
	return o
}

func (o LanHostNetworkControlPtrOutput) Elem() LanHostNetworkControlOutput {
	return o.ApplyT(func(v *LanHostNetworkControl) LanHostNetworkControl {
		if v != nil {
			return *v
		}
		var ret LanHostNetworkControl
		return ret
	}).(LanHostNetworkControlOutput)
}

func (o LanHostNetworkControlPtrOutput) CurrentMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LanHostNetworkControl) *string {
		if v == nil {
			return nil
		}
		return &v.CurrentMode
	}).(pulumi.StringPtrOutput)
}

func (o LanHostNetworkControlPtrOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LanHostNetworkControl) *string {
		if v == nil {
			return nil
		}
		return &v.Name
	}).(pulumi.StringPtrOutput)
}

func (o LanHostNetworkControlPtrOutput) ProfileId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *LanHostNetworkControl) *int {
		if v == nil {
			return nil
		}
		return &v.ProfileId
	}).(pulumi.IntPtrOutput)
}

type LanInterfaceHostRef struct {
	HostId    string         `pulumi:"hostId"`
	Interface string         `pulumi:"interface"`
	L2ident   LanHostL2Ident `pulumi:"l2ident"`
}

type LanInterfaceHostRefOutput struct{ *pulumi.OutputState }

func (LanInterfaceHostRefOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LanInterfaceHostRef)(nil)).Elem()
}

func (o LanInterfaceHostRefOutput) ToLanInterfaceHostRefOutput() LanInterfaceHostRefOutput {
	return o
}

func (o LanInterfaceHostRefOutput) ToLanInterfaceHostRefOutputWithContext(ctx context.Context) LanInterfaceHostRefOutput {
	return o
}

func (o LanInterfaceHostRefOutput) HostId() pulumi.StringOutput {
	return o.ApplyT(func(v LanInterfaceHostRef) string { return v.HostId }).(pulumi.StringOutput)
}

func (o LanInterfaceHostRefOutput) Interface() pulumi.StringOutput {
	return o.ApplyT(func(v LanInterfaceHostRef) string { return v.Interface }).(pulumi.StringOutput)
}

func (o LanInterfaceHostRefOutput) L2ident() LanHostL2IdentOutput {
	return o.ApplyT(func(v LanInterfaceHostRef) LanHostL2Ident { return v.L2ident }).(LanHostL2IdentOutput)
}

type LanInterfaceHostRefArrayOutput struct{ *pulumi.OutputState }

func (LanInterfaceHostRefArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]LanInterfaceHostRef)(nil)).Elem()
}

func (o LanInterfaceHostRefArrayOutput) ToLanInterfaceHostRefArrayOutput() LanInterfaceHostRefArrayOutput {
	return o
}

func (o LanInterfaceHostRefArrayOutput) ToLanInterfaceHostRefArrayOutputWithContext(ctx context.Context) LanInterfaceHostRefArrayOutput {
	return o
}

func (o LanInterfaceHostRefArrayOutput) Index(i pulumi.IntInput) LanInterfaceHostRefOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) LanInterfaceHostRef {
		return vs[0].([]LanInterfaceHostRef)[vs[1].(int)]
	}).(LanInterfaceHostRefOutput)
}

type LanInterfaceInfo struct {
	HostCount int    `pulumi:"hostCount"`
	Name      string `pulumi:"name"`
}

type LanInterfaceInfoOutput struct{ *pulumi.OutputState }

func (LanInterfaceInfoOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LanInterfaceInfo)(nil)).Elem()
}

func (o LanInterfaceInfoOutput) ToLanInterfaceInfoOutput() LanInterfaceInfoOutput {
	return o
}

func (o LanInterfaceInfoOutput) ToLanInterfaceInfoOutputWithContext(ctx context.Context) LanInterfaceInfoOutput {
	return o
}

func (o LanInterfaceInfoOutput) HostCount() pulumi.IntOutput {
	return o.ApplyT(func(v LanInterfaceInfo) int { return v.HostCount }).(pulumi.IntOutput)
}

func (o LanInterfaceInfoOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LanInterfaceInfo) string { return v.Name }).(pulumi.StringOutput)
}

type LanInterfaceInfoArrayOutput struct{ *pulumi.OutputState }

func (LanInterfaceInfoArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]LanInterfaceInfo)(nil)).Elem()
}

func (o LanInterfaceInfoArrayOutput) ToLanInterfaceInfoArrayOutput() LanInterfaceInfoArrayOutput {
	return o
}

func (o LanInterfaceInfoArrayOutput) ToLanInterfaceInfoArrayOutputWithContext(ctx context.Context) LanInterfaceInfoArrayOutput {
	return o
}

func (o LanInterfaceInfoArrayOutput) Index(i pulumi.IntInput) LanInterfaceInfoOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) LanInterfaceInfo {
		return vs[0].([]LanInterfaceInfo)[vs[1].(int)]
	}).(LanInterfaceInfoOutput)
}

type NetworkingBind struct {
	Interface string   `pulumi:"interface"`
	Ipv4      string   `pulumi:"ipv4"`
	Ipv6      []string `pulumi:"ipv6"`
}

type NetworkingBindOutput struct{ *pulumi.OutputState }

func (NetworkingBindOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*NetworkingBind)(nil)).Elem()
}

func (o NetworkingBindOutput) ToNetworkingBindOutput() NetworkingBindOutput {
	return o
}

func (o NetworkingBindOutput) ToNetworkingBindOutputWithContext(ctx context.Context) NetworkingBindOutput {
	return o
}

func (o NetworkingBindOutput) Interface() pulumi.StringOutput {
	return o.ApplyT(func(v NetworkingBind) string { return v.Interface }).(pulumi.StringOutput)
}

func (o NetworkingBindOutput) Ipv4() pulumi.StringOutput {
	return o.ApplyT(func(v NetworkingBind) string { return v.Ipv4 }).(pulumi.StringOutput)
}

func (o NetworkingBindOutput) Ipv6() pulumi.StringArrayOutput {
	return o.ApplyT(func(v NetworkingBind) []string { return v.Ipv6 }).(pulumi.StringArrayOutput)
}

type NetworkingBindArrayOutput struct{ *pulumi.OutputState }

func (NetworkingBindArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]NetworkingBind)(nil)).Elem()
}

func (o NetworkingBindArrayOutput) ToNetworkingBindArrayOutput() NetworkingBindArrayOutput {
	return o
}

func (o NetworkingBindArrayOutput) ToNetworkingBindArrayOutputWithContext(ctx context.Context) NetworkingBindArrayOutput {
	return o
}

func (o NetworkingBindArrayOutput) Index(i pulumi.IntInput) NetworkingBindOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) NetworkingBind {
		return vs[0].([]NetworkingBind)[vs[1].(int)]
	}).(NetworkingBindOutput)
}

type PollingSpec struct {
	Interval *int `pulumi:"interval"`
	Timeout  *int `pulumi:"timeout"`
}

// PollingSpecInput is an input type that accepts PollingSpecArgs and PollingSpecOutput values.
// You can construct a concrete instance of `PollingSpecInput` via:
//
//	PollingSpecArgs{...}
type PollingSpecInput interface {
	pulumi.Input

	ToPollingSpecOutput() PollingSpecOutput
	ToPollingSpecOutputWithContext(context.Context) PollingSpecOutput
}

type PollingSpecArgs struct {
	Interval pulumi.IntPtrInput `pulumi:"interval"`
	Timeout  pulumi.IntPtrInput `pulumi:"timeout"`
}

func (PollingSpecArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*PollingSpec)(nil)).Elem()
}

func (i PollingSpecArgs) ToPollingSpecOutput() PollingSpecOutput {
	return i.ToPollingSpecOutputWithContext(context.Background())
}

func (i PollingSpecArgs) ToPollingSpecOutputWithContext(ctx context.Context) PollingSpecOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PollingSpecOutput)
}

func (i PollingSpecArgs) ToPollingSpecPtrOutput() PollingSpecPtrOutput {
	return i.ToPollingSpecPtrOutputWithContext(context.Background())
}

func (i PollingSpecArgs) ToPollingSpecPtrOutputWithContext(ctx context.Context) PollingSpecPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PollingSpecOutput).ToPollingSpecPtrOutputWithContext(ctx)
}

// PollingSpecPtrInput is an input type that accepts PollingSpecArgs, PollingSpecPtr and PollingSpecPtrOutput values.
// You can construct a concrete instance of `PollingSpecPtrInput` via:
//
//	        PollingSpecArgs{...}
//
//	or:
//
//	        nil
type PollingSpecPtrInput interface {
	pulumi.Input

	ToPollingSpecPtrOutput() PollingSpecPtrOutput
	ToPollingSpecPtrOutputWithContext(context.Context) PollingSpecPtrOutput
}

type pollingSpecPtrType PollingSpecArgs

func PollingSpecPtr(v *PollingSpecArgs) PollingSpecPtrInput {
	return (*pollingSpecPtrType)(v)
}

func (*pollingSpecPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**PollingSpec)(nil)).Elem()
}

func (i *pollingSpecPtrType) ToPollingSpecPtrOutput() PollingSpecPtrOutput {
	return i.ToPollingSpecPtrOutputWithContext(context.Background())
}

func (i *pollingSpecPtrType) ToPollingSpecPtrOutputWithContext(ctx context.Context) PollingSpecPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PollingSpecPtrOutput)
}

type PollingSpecOutput struct{ *pulumi.OutputState }

func (PollingSpecOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*PollingSpec)(nil)).Elem()
}

func (o PollingSpecOutput) ToPollingSpecOutput() PollingSpecOutput {
	return o
}

func (o PollingSpecOutput) ToPollingSpecOutputWithContext(ctx context.Context) PollingSpecOutput {
	return o
}

func (o PollingSpecOutput) ToPollingSpecPtrOutput() PollingSpecPtrOutput {
	return o.ToPollingSpecPtrOutputWithContext(context.Background())
}

func (o PollingSpecOutput) ToPollingSpecPtrOutputWithContext(ctx context.Context) PollingSpecPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v PollingSpec) *PollingSpec {
		return &v
	}).(PollingSpecPtrOutput)
}

func (o PollingSpecOutput) Interval() pulumi.IntPtrOutput {
	return o.ApplyT(func(v PollingSpec) *int { return v.Interval }).(pulumi.IntPtrOutput)
}

func (o PollingSpecOutput) Timeout() pulumi.IntPtrOutput {
	return o.ApplyT(func(v PollingSpec) *int { return v.Timeout }).(pulumi.IntPtrOutput)
}

type PollingSpecPtrOutput struct{ *pulumi.OutputState }

func (PollingSpecPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PollingSpec)(nil)).Elem()
}

func (o PollingSpecPtrOutput) ToPollingSpecPtrOutput() PollingSpecPtrOutput {
	return o
}

func (o PollingSpecPtrOutput) ToPollingSpecPtrOutputWithContext(ctx context.Context) PollingSpecPtrOutput {
	return o
}

func (o PollingSpecPtrOutput) Elem() PollingSpecOutput {
	return o.ApplyT(func(v *PollingSpec) PollingSpec {
		if v != nil {
			return *v
		}
		var ret PollingSpec
		return ret
	}).(PollingSpecOutput)
}

func (o PollingSpecPtrOutput) Interval() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *PollingSpec) *int {
		if v == nil {
			return nil
		}
		return v.Interval
	}).(pulumi.IntPtrOutput)
}

func (o PollingSpecPtrOutput) Timeout() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *PollingSpec) *int {
		if v == nil {
			return nil
		}
		return v.Timeout
	}).(pulumi.IntPtrOutput)
}

type RemoteFileAuthentication struct {
	BasicAuth *RemoteFileBasicAuth `pulumi:"basicAuth"`
}

// RemoteFileAuthenticationInput is an input type that accepts RemoteFileAuthenticationArgs and RemoteFileAuthenticationOutput values.
// You can construct a concrete instance of `RemoteFileAuthenticationInput` via:
//
//	RemoteFileAuthenticationArgs{...}
type RemoteFileAuthenticationInput interface {
	pulumi.Input

	ToRemoteFileAuthenticationOutput() RemoteFileAuthenticationOutput
	ToRemoteFileAuthenticationOutputWithContext(context.Context) RemoteFileAuthenticationOutput
}

type RemoteFileAuthenticationArgs struct {
	BasicAuth RemoteFileBasicAuthPtrInput `pulumi:"basicAuth"`
}

func (RemoteFileAuthenticationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*RemoteFileAuthentication)(nil)).Elem()
}

func (i RemoteFileAuthenticationArgs) ToRemoteFileAuthenticationOutput() RemoteFileAuthenticationOutput {
	return i.ToRemoteFileAuthenticationOutputWithContext(context.Background())
}

func (i RemoteFileAuthenticationArgs) ToRemoteFileAuthenticationOutputWithContext(ctx context.Context) RemoteFileAuthenticationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RemoteFileAuthenticationOutput)
}

func (i RemoteFileAuthenticationArgs) ToRemoteFileAuthenticationPtrOutput() RemoteFileAuthenticationPtrOutput {
	return i.ToRemoteFileAuthenticationPtrOutputWithContext(context.Background())
}

func (i RemoteFileAuthenticationArgs) ToRemoteFileAuthenticationPtrOutputWithContext(ctx context.Context) RemoteFileAuthenticationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RemoteFileAuthenticationOutput).ToRemoteFileAuthenticationPtrOutputWithContext(ctx)
}

// RemoteFileAuthenticationPtrInput is an input type that accepts RemoteFileAuthenticationArgs, RemoteFileAuthenticationPtr and RemoteFileAuthenticationPtrOutput values.
// You can construct a concrete instance of `RemoteFileAuthenticationPtrInput` via:
//
//	        RemoteFileAuthenticationArgs{...}
//
//	or:
//
//	        nil
type RemoteFileAuthenticationPtrInput interface {
	pulumi.Input

	ToRemoteFileAuthenticationPtrOutput() RemoteFileAuthenticationPtrOutput
	ToRemoteFileAuthenticationPtrOutputWithContext(context.Context) RemoteFileAuthenticationPtrOutput
}

type remoteFileAuthenticationPtrType RemoteFileAuthenticationArgs

func RemoteFileAuthenticationPtr(v *RemoteFileAuthenticationArgs) RemoteFileAuthenticationPtrInput {
	return (*remoteFileAuthenticationPtrType)(v)
}

func (*remoteFileAuthenticationPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**RemoteFileAuthentication)(nil)).Elem()
}

func (i *remoteFileAuthenticationPtrType) ToRemoteFileAuthenticationPtrOutput() RemoteFileAuthenticationPtrOutput {
	return i.ToRemoteFileAuthenticationPtrOutputWithContext(context.Background())
}

func (i *remoteFileAuthenticationPtrType) ToRemoteFileAuthenticationPtrOutputWithContext(ctx context.Context) RemoteFileAuthenticationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RemoteFileAuthenticationPtrOutput)
}

type RemoteFileAuthenticationOutput struct{ *pulumi.OutputState }

func (RemoteFileAuthenticationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RemoteFileAuthentication)(nil)).Elem()
}

func (o RemoteFileAuthenticationOutput) ToRemoteFileAuthenticationOutput() RemoteFileAuthenticationOutput {
	return o
}

func (o RemoteFileAuthenticationOutput) ToRemoteFileAuthenticationOutputWithContext(ctx context.Context) RemoteFileAuthenticationOutput {
	return o
}

func (o RemoteFileAuthenticationOutput) ToRemoteFileAuthenticationPtrOutput() RemoteFileAuthenticationPtrOutput {
	return o.ToRemoteFileAuthenticationPtrOutputWithContext(context.Background())
}

func (o RemoteFileAuthenticationOutput) ToRemoteFileAuthenticationPtrOutputWithContext(ctx context.Context) RemoteFileAuthenticationPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v RemoteFileAuthentication) *RemoteFileAuthentication {
		return &v
	}).(RemoteFileAuthenticationPtrOutput)
}

func (o RemoteFileAuthenticationOutput) BasicAuth() RemoteFileBasicAuthPtrOutput {
	return o.ApplyT(func(v RemoteFileAuthentication) *RemoteFileBasicAuth { return v.BasicAuth }).(RemoteFileBasicAuthPtrOutput)
}

type RemoteFileAuthenticationPtrOutput struct{ *pulumi.OutputState }

func (RemoteFileAuthenticationPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RemoteFileAuthentication)(nil)).Elem()
}

func (o RemoteFileAuthenticationPtrOutput) ToRemoteFileAuthenticationPtrOutput() RemoteFileAuthenticationPtrOutput {
	return o
}

func (o RemoteFileAuthenticationPtrOutput) ToRemoteFileAuthenticationPtrOutputWithContext(ctx context.Context) RemoteFileAuthenticationPtrOutput {
	return o
}

func (o RemoteFileAuthenticationPtrOutput) Elem() RemoteFileAuthenticationOutput {
	return o.ApplyT(func(v *RemoteFileAuthentication) RemoteFileAuthentication {
		if v != nil {
			return *v
		}
		var ret RemoteFileAuthentication
		return ret
	}).(RemoteFileAuthenticationOutput)
}

func (o RemoteFileAuthenticationPtrOutput) BasicAuth() RemoteFileBasicAuthPtrOutput {
	return o.ApplyT(func(v *RemoteFileAuthentication) *RemoteFileBasicAuth {
		if v == nil {
			return nil
		}
		return v.BasicAuth
	}).(RemoteFileBasicAuthPtrOutput)
}

type RemoteFileBasicAuth struct {
	Password *string `pulumi:"password"`
	Username *string `pulumi:"username"`
}

// RemoteFileBasicAuthInput is an input type that accepts RemoteFileBasicAuthArgs and RemoteFileBasicAuthOutput values.
// You can construct a concrete instance of `RemoteFileBasicAuthInput` via:
//
//	RemoteFileBasicAuthArgs{...}
type RemoteFileBasicAuthInput interface {
	pulumi.Input

	ToRemoteFileBasicAuthOutput() RemoteFileBasicAuthOutput
	ToRemoteFileBasicAuthOutputWithContext(context.Context) RemoteFileBasicAuthOutput
}

type RemoteFileBasicAuthArgs struct {
	Password pulumi.StringPtrInput `pulumi:"password"`
	Username pulumi.StringPtrInput `pulumi:"username"`
}

func (RemoteFileBasicAuthArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*RemoteFileBasicAuth)(nil)).Elem()
}

func (i RemoteFileBasicAuthArgs) ToRemoteFileBasicAuthOutput() RemoteFileBasicAuthOutput {
	return i.ToRemoteFileBasicAuthOutputWithContext(context.Background())
}

func (i RemoteFileBasicAuthArgs) ToRemoteFileBasicAuthOutputWithContext(ctx context.Context) RemoteFileBasicAuthOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RemoteFileBasicAuthOutput)
}

func (i RemoteFileBasicAuthArgs) ToRemoteFileBasicAuthPtrOutput() RemoteFileBasicAuthPtrOutput {
	return i.ToRemoteFileBasicAuthPtrOutputWithContext(context.Background())
}

func (i RemoteFileBasicAuthArgs) ToRemoteFileBasicAuthPtrOutputWithContext(ctx context.Context) RemoteFileBasicAuthPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RemoteFileBasicAuthOutput).ToRemoteFileBasicAuthPtrOutputWithContext(ctx)
}

// RemoteFileBasicAuthPtrInput is an input type that accepts RemoteFileBasicAuthArgs, RemoteFileBasicAuthPtr and RemoteFileBasicAuthPtrOutput values.
// You can construct a concrete instance of `RemoteFileBasicAuthPtrInput` via:
//
//	        RemoteFileBasicAuthArgs{...}
//
//	or:
//
//	        nil
type RemoteFileBasicAuthPtrInput interface {
	pulumi.Input

	ToRemoteFileBasicAuthPtrOutput() RemoteFileBasicAuthPtrOutput
	ToRemoteFileBasicAuthPtrOutputWithContext(context.Context) RemoteFileBasicAuthPtrOutput
}

type remoteFileBasicAuthPtrType RemoteFileBasicAuthArgs

func RemoteFileBasicAuthPtr(v *RemoteFileBasicAuthArgs) RemoteFileBasicAuthPtrInput {
	return (*remoteFileBasicAuthPtrType)(v)
}

func (*remoteFileBasicAuthPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**RemoteFileBasicAuth)(nil)).Elem()
}

func (i *remoteFileBasicAuthPtrType) ToRemoteFileBasicAuthPtrOutput() RemoteFileBasicAuthPtrOutput {
	return i.ToRemoteFileBasicAuthPtrOutputWithContext(context.Background())
}

func (i *remoteFileBasicAuthPtrType) ToRemoteFileBasicAuthPtrOutputWithContext(ctx context.Context) RemoteFileBasicAuthPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RemoteFileBasicAuthPtrOutput)
}

type RemoteFileBasicAuthOutput struct{ *pulumi.OutputState }

func (RemoteFileBasicAuthOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RemoteFileBasicAuth)(nil)).Elem()
}

func (o RemoteFileBasicAuthOutput) ToRemoteFileBasicAuthOutput() RemoteFileBasicAuthOutput {
	return o
}

func (o RemoteFileBasicAuthOutput) ToRemoteFileBasicAuthOutputWithContext(ctx context.Context) RemoteFileBasicAuthOutput {
	return o
}

func (o RemoteFileBasicAuthOutput) ToRemoteFileBasicAuthPtrOutput() RemoteFileBasicAuthPtrOutput {
	return o.ToRemoteFileBasicAuthPtrOutputWithContext(context.Background())
}

func (o RemoteFileBasicAuthOutput) ToRemoteFileBasicAuthPtrOutputWithContext(ctx context.Context) RemoteFileBasicAuthPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v RemoteFileBasicAuth) *RemoteFileBasicAuth {
		return &v
	}).(RemoteFileBasicAuthPtrOutput)
}

func (o RemoteFileBasicAuthOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v RemoteFileBasicAuth) *string { return v.Password }).(pulumi.StringPtrOutput)
}

func (o RemoteFileBasicAuthOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v RemoteFileBasicAuth) *string { return v.Username }).(pulumi.StringPtrOutput)
}

type RemoteFileBasicAuthPtrOutput struct{ *pulumi.OutputState }

func (RemoteFileBasicAuthPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RemoteFileBasicAuth)(nil)).Elem()
}

func (o RemoteFileBasicAuthPtrOutput) ToRemoteFileBasicAuthPtrOutput() RemoteFileBasicAuthPtrOutput {
	return o
}

func (o RemoteFileBasicAuthPtrOutput) ToRemoteFileBasicAuthPtrOutputWithContext(ctx context.Context) RemoteFileBasicAuthPtrOutput {
	return o
}

func (o RemoteFileBasicAuthPtrOutput) Elem() RemoteFileBasicAuthOutput {
	return o.ApplyT(func(v *RemoteFileBasicAuth) RemoteFileBasicAuth {
		if v != nil {
			return *v
		}
		var ret RemoteFileBasicAuth
		return ret
	}).(RemoteFileBasicAuthOutput)
}

func (o RemoteFileBasicAuthPtrOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RemoteFileBasicAuth) *string {
		if v == nil {
			return nil
		}
		return v.Password
	}).(pulumi.StringPtrOutput)
}

func (o RemoteFileBasicAuthPtrOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RemoteFileBasicAuth) *string {
		if v == nil {
			return nil
		}
		return v.Username
	}).(pulumi.StringPtrOutput)
}

type RemoteFileExtract struct {
	DestinationPath *string `pulumi:"destinationPath"`
	Overwrite       *bool   `pulumi:"overwrite"`
	Password        *string `pulumi:"password"`
}

// RemoteFileExtractInput is an input type that accepts RemoteFileExtractArgs and RemoteFileExtractOutput values.
// You can construct a concrete instance of `RemoteFileExtractInput` via:
//
//	RemoteFileExtractArgs{...}
type RemoteFileExtractInput interface {
	pulumi.Input

	ToRemoteFileExtractOutput() RemoteFileExtractOutput
	ToRemoteFileExtractOutputWithContext(context.Context) RemoteFileExtractOutput
}

type RemoteFileExtractArgs struct {
	DestinationPath pulumi.StringPtrInput `pulumi:"destinationPath"`
	Overwrite       pulumi.BoolPtrInput   `pulumi:"overwrite"`
	Password        pulumi.StringPtrInput `pulumi:"password"`
}

func (RemoteFileExtractArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*RemoteFileExtract)(nil)).Elem()
}

func (i RemoteFileExtractArgs) ToRemoteFileExtractOutput() RemoteFileExtractOutput {
	return i.ToRemoteFileExtractOutputWithContext(context.Background())
}

func (i RemoteFileExtractArgs) ToRemoteFileExtractOutputWithContext(ctx context.Context) RemoteFileExtractOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RemoteFileExtractOutput)
}

func (i RemoteFileExtractArgs) ToRemoteFileExtractPtrOutput() RemoteFileExtractPtrOutput {
	return i.ToRemoteFileExtractPtrOutputWithContext(context.Background())
}

func (i RemoteFileExtractArgs) ToRemoteFileExtractPtrOutputWithContext(ctx context.Context) RemoteFileExtractPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RemoteFileExtractOutput).ToRemoteFileExtractPtrOutputWithContext(ctx)
}

// RemoteFileExtractPtrInput is an input type that accepts RemoteFileExtractArgs, RemoteFileExtractPtr and RemoteFileExtractPtrOutput values.
// You can construct a concrete instance of `RemoteFileExtractPtrInput` via:
//
//	        RemoteFileExtractArgs{...}
//
//	or:
//
//	        nil
type RemoteFileExtractPtrInput interface {
	pulumi.Input

	ToRemoteFileExtractPtrOutput() RemoteFileExtractPtrOutput
	ToRemoteFileExtractPtrOutputWithContext(context.Context) RemoteFileExtractPtrOutput
}

type remoteFileExtractPtrType RemoteFileExtractArgs

func RemoteFileExtractPtr(v *RemoteFileExtractArgs) RemoteFileExtractPtrInput {
	return (*remoteFileExtractPtrType)(v)
}

func (*remoteFileExtractPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**RemoteFileExtract)(nil)).Elem()
}

func (i *remoteFileExtractPtrType) ToRemoteFileExtractPtrOutput() RemoteFileExtractPtrOutput {
	return i.ToRemoteFileExtractPtrOutputWithContext(context.Background())
}

func (i *remoteFileExtractPtrType) ToRemoteFileExtractPtrOutputWithContext(ctx context.Context) RemoteFileExtractPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RemoteFileExtractPtrOutput)
}

type RemoteFileExtractOutput struct{ *pulumi.OutputState }

func (RemoteFileExtractOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RemoteFileExtract)(nil)).Elem()
}

func (o RemoteFileExtractOutput) ToRemoteFileExtractOutput() RemoteFileExtractOutput {
	return o
}

func (o RemoteFileExtractOutput) ToRemoteFileExtractOutputWithContext(ctx context.Context) RemoteFileExtractOutput {
	return o
}

func (o RemoteFileExtractOutput) ToRemoteFileExtractPtrOutput() RemoteFileExtractPtrOutput {
	return o.ToRemoteFileExtractPtrOutputWithContext(context.Background())
}

func (o RemoteFileExtractOutput) ToRemoteFileExtractPtrOutputWithContext(ctx context.Context) RemoteFileExtractPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v RemoteFileExtract) *RemoteFileExtract {
		return &v
	}).(RemoteFileExtractPtrOutput)
}

func (o RemoteFileExtractOutput) DestinationPath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v RemoteFileExtract) *string { return v.DestinationPath }).(pulumi.StringPtrOutput)
}

func (o RemoteFileExtractOutput) Overwrite() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v RemoteFileExtract) *bool { return v.Overwrite }).(pulumi.BoolPtrOutput)
}

func (o RemoteFileExtractOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v RemoteFileExtract) *string { return v.Password }).(pulumi.StringPtrOutput)
}

type RemoteFileExtractPtrOutput struct{ *pulumi.OutputState }

func (RemoteFileExtractPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RemoteFileExtract)(nil)).Elem()
}

func (o RemoteFileExtractPtrOutput) ToRemoteFileExtractPtrOutput() RemoteFileExtractPtrOutput {
	return o
}

func (o RemoteFileExtractPtrOutput) ToRemoteFileExtractPtrOutputWithContext(ctx context.Context) RemoteFileExtractPtrOutput {
	return o
}

func (o RemoteFileExtractPtrOutput) Elem() RemoteFileExtractOutput {
	return o.ApplyT(func(v *RemoteFileExtract) RemoteFileExtract {
		if v != nil {
			return *v
		}
		var ret RemoteFileExtract
		return ret
	}).(RemoteFileExtractOutput)
}

func (o RemoteFileExtractPtrOutput) DestinationPath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RemoteFileExtract) *string {
		if v == nil {
			return nil
		}
		return v.DestinationPath
	}).(pulumi.StringPtrOutput)
}

func (o RemoteFileExtractPtrOutput) Overwrite() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *RemoteFileExtract) *bool {
		if v == nil {
			return nil
		}
		return v.Overwrite
	}).(pulumi.BoolPtrOutput)
}

func (o RemoteFileExtractPtrOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RemoteFileExtract) *string {
		if v == nil {
			return nil
		}
		return v.Password
	}).(pulumi.StringPtrOutput)
}

type RemoteFilePolling struct {
	ChecksumCompute *PollingSpec `pulumi:"checksumCompute"`
	Copy            *PollingSpec `pulumi:"copy"`
	Delete          *PollingSpec `pulumi:"delete"`
	Download        *PollingSpec `pulumi:"download"`
	Extract         *PollingSpec `pulumi:"extract"`
	Move            *PollingSpec `pulumi:"move"`
	Upload          *PollingSpec `pulumi:"upload"`
}

// RemoteFilePollingInput is an input type that accepts RemoteFilePollingArgs and RemoteFilePollingOutput values.
// You can construct a concrete instance of `RemoteFilePollingInput` via:
//
//	RemoteFilePollingArgs{...}
type RemoteFilePollingInput interface {
	pulumi.Input

	ToRemoteFilePollingOutput() RemoteFilePollingOutput
	ToRemoteFilePollingOutputWithContext(context.Context) RemoteFilePollingOutput
}

type RemoteFilePollingArgs struct {
	ChecksumCompute PollingSpecPtrInput `pulumi:"checksumCompute"`
	Copy            PollingSpecPtrInput `pulumi:"copy"`
	Delete          PollingSpecPtrInput `pulumi:"delete"`
	Download        PollingSpecPtrInput `pulumi:"download"`
	Extract         PollingSpecPtrInput `pulumi:"extract"`
	Move            PollingSpecPtrInput `pulumi:"move"`
	Upload          PollingSpecPtrInput `pulumi:"upload"`
}

func (RemoteFilePollingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*RemoteFilePolling)(nil)).Elem()
}

func (i RemoteFilePollingArgs) ToRemoteFilePollingOutput() RemoteFilePollingOutput {
	return i.ToRemoteFilePollingOutputWithContext(context.Background())
}

func (i RemoteFilePollingArgs) ToRemoteFilePollingOutputWithContext(ctx context.Context) RemoteFilePollingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RemoteFilePollingOutput)
}

func (i RemoteFilePollingArgs) ToRemoteFilePollingPtrOutput() RemoteFilePollingPtrOutput {
	return i.ToRemoteFilePollingPtrOutputWithContext(context.Background())
}

func (i RemoteFilePollingArgs) ToRemoteFilePollingPtrOutputWithContext(ctx context.Context) RemoteFilePollingPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RemoteFilePollingOutput).ToRemoteFilePollingPtrOutputWithContext(ctx)
}

// RemoteFilePollingPtrInput is an input type that accepts RemoteFilePollingArgs, RemoteFilePollingPtr and RemoteFilePollingPtrOutput values.
// You can construct a concrete instance of `RemoteFilePollingPtrInput` via:
//
//	        RemoteFilePollingArgs{...}
//
//	or:
//
//	        nil
type RemoteFilePollingPtrInput interface {
	pulumi.Input

	ToRemoteFilePollingPtrOutput() RemoteFilePollingPtrOutput
	ToRemoteFilePollingPtrOutputWithContext(context.Context) RemoteFilePollingPtrOutput
}

type remoteFilePollingPtrType RemoteFilePollingArgs

func RemoteFilePollingPtr(v *RemoteFilePollingArgs) RemoteFilePollingPtrInput {
	return (*remoteFilePollingPtrType)(v)
}

func (*remoteFilePollingPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**RemoteFilePolling)(nil)).Elem()
}

func (i *remoteFilePollingPtrType) ToRemoteFilePollingPtrOutput() RemoteFilePollingPtrOutput {
	return i.ToRemoteFilePollingPtrOutputWithContext(context.Background())
}

func (i *remoteFilePollingPtrType) ToRemoteFilePollingPtrOutputWithContext(ctx context.Context) RemoteFilePollingPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RemoteFilePollingPtrOutput)
}

type RemoteFilePollingOutput struct{ *pulumi.OutputState }

func (RemoteFilePollingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RemoteFilePolling)(nil)).Elem()
}

func (o RemoteFilePollingOutput) ToRemoteFilePollingOutput() RemoteFilePollingOutput {
	return o
}

func (o RemoteFilePollingOutput) ToRemoteFilePollingOutputWithContext(ctx context.Context) RemoteFilePollingOutput {
	return o
}

func (o RemoteFilePollingOutput) ToRemoteFilePollingPtrOutput() RemoteFilePollingPtrOutput {
	return o.ToRemoteFilePollingPtrOutputWithContext(context.Background())
}

func (o RemoteFilePollingOutput) ToRemoteFilePollingPtrOutputWithContext(ctx context.Context) RemoteFilePollingPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v RemoteFilePolling) *RemoteFilePolling {
		return &v
	}).(RemoteFilePollingPtrOutput)
}

func (o RemoteFilePollingOutput) ChecksumCompute() PollingSpecPtrOutput {
	return o.ApplyT(func(v RemoteFilePolling) *PollingSpec { return v.ChecksumCompute }).(PollingSpecPtrOutput)
}

func (o RemoteFilePollingOutput) Copy() PollingSpecPtrOutput {
	return o.ApplyT(func(v RemoteFilePolling) *PollingSpec { return v.Copy }).(PollingSpecPtrOutput)
}

func (o RemoteFilePollingOutput) Delete() PollingSpecPtrOutput {
	return o.ApplyT(func(v RemoteFilePolling) *PollingSpec { return v.Delete }).(PollingSpecPtrOutput)
}

func (o RemoteFilePollingOutput) Download() PollingSpecPtrOutput {
	return o.ApplyT(func(v RemoteFilePolling) *PollingSpec { return v.Download }).(PollingSpecPtrOutput)
}

func (o RemoteFilePollingOutput) Extract() PollingSpecPtrOutput {
	return o.ApplyT(func(v RemoteFilePolling) *PollingSpec { return v.Extract }).(PollingSpecPtrOutput)
}

func (o RemoteFilePollingOutput) Move() PollingSpecPtrOutput {
	return o.ApplyT(func(v RemoteFilePolling) *PollingSpec { return v.Move }).(PollingSpecPtrOutput)
}

func (o RemoteFilePollingOutput) Upload() PollingSpecPtrOutput {
	return o.ApplyT(func(v RemoteFilePolling) *PollingSpec { return v.Upload }).(PollingSpecPtrOutput)
}

type RemoteFilePollingPtrOutput struct{ *pulumi.OutputState }

func (RemoteFilePollingPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RemoteFilePolling)(nil)).Elem()
}

func (o RemoteFilePollingPtrOutput) ToRemoteFilePollingPtrOutput() RemoteFilePollingPtrOutput {
	return o
}

func (o RemoteFilePollingPtrOutput) ToRemoteFilePollingPtrOutputWithContext(ctx context.Context) RemoteFilePollingPtrOutput {
	return o
}

func (o RemoteFilePollingPtrOutput) Elem() RemoteFilePollingOutput {
	return o.ApplyT(func(v *RemoteFilePolling) RemoteFilePolling {
		if v != nil {
			return *v
		}
		var ret RemoteFilePolling
		return ret
	}).(RemoteFilePollingOutput)
}

func (o RemoteFilePollingPtrOutput) ChecksumCompute() PollingSpecPtrOutput {
	return o.ApplyT(func(v *RemoteFilePolling) *PollingSpec {
		if v == nil {
			return nil
		}
		return v.ChecksumCompute
	}).(PollingSpecPtrOutput)
}

func (o RemoteFilePollingPtrOutput) Copy() PollingSpecPtrOutput {
	return o.ApplyT(func(v *RemoteFilePolling) *PollingSpec {
		if v == nil {
			return nil
		}
		return v.Copy
	}).(PollingSpecPtrOutput)
}

func (o RemoteFilePollingPtrOutput) Delete() PollingSpecPtrOutput {
	return o.ApplyT(func(v *RemoteFilePolling) *PollingSpec {
		if v == nil {
			return nil
		}
		return v.Delete
	}).(PollingSpecPtrOutput)
}

func (o RemoteFilePollingPtrOutput) Download() PollingSpecPtrOutput {
	return o.ApplyT(func(v *RemoteFilePolling) *PollingSpec {
		if v == nil {
			return nil
		}
		return v.Download
	}).(PollingSpecPtrOutput)
}

func (o RemoteFilePollingPtrOutput) Extract() PollingSpecPtrOutput {
	return o.ApplyT(func(v *RemoteFilePolling) *PollingSpec {
		if v == nil {
			return nil
		}
		return v.Extract
	}).(PollingSpecPtrOutput)
}

func (o RemoteFilePollingPtrOutput) Move() PollingSpecPtrOutput {
	return o.ApplyT(func(v *RemoteFilePolling) *PollingSpec {
		if v == nil {
			return nil
		}
		return v.Move
	}).(PollingSpecPtrOutput)
}

func (o RemoteFilePollingPtrOutput) Upload() PollingSpecPtrOutput {
	return o.ApplyT(func(v *RemoteFilePolling) *PollingSpec {
		if v == nil {
			return nil
		}
		return v.Upload
	}).(PollingSpecPtrOutput)
}

type VirtualDiskPolling struct {
	Checksum *PollingSpec `pulumi:"checksum"`
	Copy     *PollingSpec `pulumi:"copy"`
	Create   *PollingSpec `pulumi:"create"`
	Delete   *PollingSpec `pulumi:"delete"`
	Move     *PollingSpec `pulumi:"move"`
	Resize   *PollingSpec `pulumi:"resize"`
}

// VirtualDiskPollingInput is an input type that accepts VirtualDiskPollingArgs and VirtualDiskPollingOutput values.
// You can construct a concrete instance of `VirtualDiskPollingInput` via:
//
//	VirtualDiskPollingArgs{...}
type VirtualDiskPollingInput interface {
	pulumi.Input

	ToVirtualDiskPollingOutput() VirtualDiskPollingOutput
	ToVirtualDiskPollingOutputWithContext(context.Context) VirtualDiskPollingOutput
}

type VirtualDiskPollingArgs struct {
	Checksum PollingSpecPtrInput `pulumi:"checksum"`
	Copy     PollingSpecPtrInput `pulumi:"copy"`
	Create   PollingSpecPtrInput `pulumi:"create"`
	Delete   PollingSpecPtrInput `pulumi:"delete"`
	Move     PollingSpecPtrInput `pulumi:"move"`
	Resize   PollingSpecPtrInput `pulumi:"resize"`
}

func (VirtualDiskPollingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualDiskPolling)(nil)).Elem()
}

func (i VirtualDiskPollingArgs) ToVirtualDiskPollingOutput() VirtualDiskPollingOutput {
	return i.ToVirtualDiskPollingOutputWithContext(context.Background())
}

func (i VirtualDiskPollingArgs) ToVirtualDiskPollingOutputWithContext(ctx context.Context) VirtualDiskPollingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualDiskPollingOutput)
}

func (i VirtualDiskPollingArgs) ToVirtualDiskPollingPtrOutput() VirtualDiskPollingPtrOutput {
	return i.ToVirtualDiskPollingPtrOutputWithContext(context.Background())
}

func (i VirtualDiskPollingArgs) ToVirtualDiskPollingPtrOutputWithContext(ctx context.Context) VirtualDiskPollingPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualDiskPollingOutput).ToVirtualDiskPollingPtrOutputWithContext(ctx)
}

// VirtualDiskPollingPtrInput is an input type that accepts VirtualDiskPollingArgs, VirtualDiskPollingPtr and VirtualDiskPollingPtrOutput values.
// You can construct a concrete instance of `VirtualDiskPollingPtrInput` via:
//
//	        VirtualDiskPollingArgs{...}
//
//	or:
//
//	        nil
type VirtualDiskPollingPtrInput interface {
	pulumi.Input

	ToVirtualDiskPollingPtrOutput() VirtualDiskPollingPtrOutput
	ToVirtualDiskPollingPtrOutputWithContext(context.Context) VirtualDiskPollingPtrOutput
}

type virtualDiskPollingPtrType VirtualDiskPollingArgs

func VirtualDiskPollingPtr(v *VirtualDiskPollingArgs) VirtualDiskPollingPtrInput {
	return (*virtualDiskPollingPtrType)(v)
}

func (*virtualDiskPollingPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualDiskPolling)(nil)).Elem()
}

func (i *virtualDiskPollingPtrType) ToVirtualDiskPollingPtrOutput() VirtualDiskPollingPtrOutput {
	return i.ToVirtualDiskPollingPtrOutputWithContext(context.Background())
}

func (i *virtualDiskPollingPtrType) ToVirtualDiskPollingPtrOutputWithContext(ctx context.Context) VirtualDiskPollingPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualDiskPollingPtrOutput)
}

type VirtualDiskPollingOutput struct{ *pulumi.OutputState }

func (VirtualDiskPollingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualDiskPolling)(nil)).Elem()
}

func (o VirtualDiskPollingOutput) ToVirtualDiskPollingOutput() VirtualDiskPollingOutput {
	return o
}

func (o VirtualDiskPollingOutput) ToVirtualDiskPollingOutputWithContext(ctx context.Context) VirtualDiskPollingOutput {
	return o
}

func (o VirtualDiskPollingOutput) ToVirtualDiskPollingPtrOutput() VirtualDiskPollingPtrOutput {
	return o.ToVirtualDiskPollingPtrOutputWithContext(context.Background())
}

func (o VirtualDiskPollingOutput) ToVirtualDiskPollingPtrOutputWithContext(ctx context.Context) VirtualDiskPollingPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v VirtualDiskPolling) *VirtualDiskPolling {
		return &v
	}).(VirtualDiskPollingPtrOutput)
}

func (o VirtualDiskPollingOutput) Checksum() PollingSpecPtrOutput {
	return o.ApplyT(func(v VirtualDiskPolling) *PollingSpec { return v.Checksum }).(PollingSpecPtrOutput)
}

func (o VirtualDiskPollingOutput) Copy() PollingSpecPtrOutput {
	return o.ApplyT(func(v VirtualDiskPolling) *PollingSpec { return v.Copy }).(PollingSpecPtrOutput)
}

func (o VirtualDiskPollingOutput) Create() PollingSpecPtrOutput {
	return o.ApplyT(func(v VirtualDiskPolling) *PollingSpec { return v.Create }).(PollingSpecPtrOutput)
}

func (o VirtualDiskPollingOutput) Delete() PollingSpecPtrOutput {
	return o.ApplyT(func(v VirtualDiskPolling) *PollingSpec { return v.Delete }).(PollingSpecPtrOutput)
}

func (o VirtualDiskPollingOutput) Move() PollingSpecPtrOutput {
	return o.ApplyT(func(v VirtualDiskPolling) *PollingSpec { return v.Move }).(PollingSpecPtrOutput)
}

func (o VirtualDiskPollingOutput) Resize() PollingSpecPtrOutput {
	return o.ApplyT(func(v VirtualDiskPolling) *PollingSpec { return v.Resize }).(PollingSpecPtrOutput)
}

type VirtualDiskPollingPtrOutput struct{ *pulumi.OutputState }

func (VirtualDiskPollingPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualDiskPolling)(nil)).Elem()
}

func (o VirtualDiskPollingPtrOutput) ToVirtualDiskPollingPtrOutput() VirtualDiskPollingPtrOutput {
	return o
}

func (o VirtualDiskPollingPtrOutput) ToVirtualDiskPollingPtrOutputWithContext(ctx context.Context) VirtualDiskPollingPtrOutput {
	return o
}

func (o VirtualDiskPollingPtrOutput) Elem() VirtualDiskPollingOutput {
	return o.ApplyT(func(v *VirtualDiskPolling) VirtualDiskPolling {
		if v != nil {
			return *v
		}
		var ret VirtualDiskPolling
		return ret
	}).(VirtualDiskPollingOutput)
}

func (o VirtualDiskPollingPtrOutput) Checksum() PollingSpecPtrOutput {
	return o.ApplyT(func(v *VirtualDiskPolling) *PollingSpec {
		if v == nil {
			return nil
		}
		return v.Checksum
	}).(PollingSpecPtrOutput)
}

func (o VirtualDiskPollingPtrOutput) Copy() PollingSpecPtrOutput {
	return o.ApplyT(func(v *VirtualDiskPolling) *PollingSpec {
		if v == nil {
			return nil
		}
		return v.Copy
	}).(PollingSpecPtrOutput)
}

func (o VirtualDiskPollingPtrOutput) Create() PollingSpecPtrOutput {
	return o.ApplyT(func(v *VirtualDiskPolling) *PollingSpec {
		if v == nil {
			return nil
		}
		return v.Create
	}).(PollingSpecPtrOutput)
}

func (o VirtualDiskPollingPtrOutput) Delete() PollingSpecPtrOutput {
	return o.ApplyT(func(v *VirtualDiskPolling) *PollingSpec {
		if v == nil {
			return nil
		}
		return v.Delete
	}).(PollingSpecPtrOutput)
}

func (o VirtualDiskPollingPtrOutput) Move() PollingSpecPtrOutput {
	return o.ApplyT(func(v *VirtualDiskPolling) *PollingSpec {
		if v == nil {
			return nil
		}
		return v.Move
	}).(PollingSpecPtrOutput)
}

func (o VirtualDiskPollingPtrOutput) Resize() PollingSpecPtrOutput {
	return o.ApplyT(func(v *VirtualDiskPolling) *PollingSpec {
		if v == nil {
			return nil
		}
		return v.Resize
	}).(PollingSpecPtrOutput)
}

type VirtualMachinePowerTimeouts struct {
	Kill *int `pulumi:"kill"`
}

// VirtualMachinePowerTimeoutsInput is an input type that accepts VirtualMachinePowerTimeoutsArgs and VirtualMachinePowerTimeoutsOutput values.
// You can construct a concrete instance of `VirtualMachinePowerTimeoutsInput` via:
//
//	VirtualMachinePowerTimeoutsArgs{...}
type VirtualMachinePowerTimeoutsInput interface {
	pulumi.Input

	ToVirtualMachinePowerTimeoutsOutput() VirtualMachinePowerTimeoutsOutput
	ToVirtualMachinePowerTimeoutsOutputWithContext(context.Context) VirtualMachinePowerTimeoutsOutput
}

type VirtualMachinePowerTimeoutsArgs struct {
	Kill pulumi.IntPtrInput `pulumi:"kill"`
}

func (VirtualMachinePowerTimeoutsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualMachinePowerTimeouts)(nil)).Elem()
}

func (i VirtualMachinePowerTimeoutsArgs) ToVirtualMachinePowerTimeoutsOutput() VirtualMachinePowerTimeoutsOutput {
	return i.ToVirtualMachinePowerTimeoutsOutputWithContext(context.Background())
}

func (i VirtualMachinePowerTimeoutsArgs) ToVirtualMachinePowerTimeoutsOutputWithContext(ctx context.Context) VirtualMachinePowerTimeoutsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualMachinePowerTimeoutsOutput)
}

func (i VirtualMachinePowerTimeoutsArgs) ToVirtualMachinePowerTimeoutsPtrOutput() VirtualMachinePowerTimeoutsPtrOutput {
	return i.ToVirtualMachinePowerTimeoutsPtrOutputWithContext(context.Background())
}

func (i VirtualMachinePowerTimeoutsArgs) ToVirtualMachinePowerTimeoutsPtrOutputWithContext(ctx context.Context) VirtualMachinePowerTimeoutsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualMachinePowerTimeoutsOutput).ToVirtualMachinePowerTimeoutsPtrOutputWithContext(ctx)
}

// VirtualMachinePowerTimeoutsPtrInput is an input type that accepts VirtualMachinePowerTimeoutsArgs, VirtualMachinePowerTimeoutsPtr and VirtualMachinePowerTimeoutsPtrOutput values.
// You can construct a concrete instance of `VirtualMachinePowerTimeoutsPtrInput` via:
//
//	        VirtualMachinePowerTimeoutsArgs{...}
//
//	or:
//
//	        nil
type VirtualMachinePowerTimeoutsPtrInput interface {
	pulumi.Input

	ToVirtualMachinePowerTimeoutsPtrOutput() VirtualMachinePowerTimeoutsPtrOutput
	ToVirtualMachinePowerTimeoutsPtrOutputWithContext(context.Context) VirtualMachinePowerTimeoutsPtrOutput
}

type virtualMachinePowerTimeoutsPtrType VirtualMachinePowerTimeoutsArgs

func VirtualMachinePowerTimeoutsPtr(v *VirtualMachinePowerTimeoutsArgs) VirtualMachinePowerTimeoutsPtrInput {
	return (*virtualMachinePowerTimeoutsPtrType)(v)
}

func (*virtualMachinePowerTimeoutsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualMachinePowerTimeouts)(nil)).Elem()
}

func (i *virtualMachinePowerTimeoutsPtrType) ToVirtualMachinePowerTimeoutsPtrOutput() VirtualMachinePowerTimeoutsPtrOutput {
	return i.ToVirtualMachinePowerTimeoutsPtrOutputWithContext(context.Background())
}

func (i *virtualMachinePowerTimeoutsPtrType) ToVirtualMachinePowerTimeoutsPtrOutputWithContext(ctx context.Context) VirtualMachinePowerTimeoutsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualMachinePowerTimeoutsPtrOutput)
}

type VirtualMachinePowerTimeoutsOutput struct{ *pulumi.OutputState }

func (VirtualMachinePowerTimeoutsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualMachinePowerTimeouts)(nil)).Elem()
}

func (o VirtualMachinePowerTimeoutsOutput) ToVirtualMachinePowerTimeoutsOutput() VirtualMachinePowerTimeoutsOutput {
	return o
}

func (o VirtualMachinePowerTimeoutsOutput) ToVirtualMachinePowerTimeoutsOutputWithContext(ctx context.Context) VirtualMachinePowerTimeoutsOutput {
	return o
}

func (o VirtualMachinePowerTimeoutsOutput) ToVirtualMachinePowerTimeoutsPtrOutput() VirtualMachinePowerTimeoutsPtrOutput {
	return o.ToVirtualMachinePowerTimeoutsPtrOutputWithContext(context.Background())
}

func (o VirtualMachinePowerTimeoutsOutput) ToVirtualMachinePowerTimeoutsPtrOutputWithContext(ctx context.Context) VirtualMachinePowerTimeoutsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v VirtualMachinePowerTimeouts) *VirtualMachinePowerTimeouts {
		return &v
	}).(VirtualMachinePowerTimeoutsPtrOutput)
}

func (o VirtualMachinePowerTimeoutsOutput) Kill() pulumi.IntPtrOutput {
	return o.ApplyT(func(v VirtualMachinePowerTimeouts) *int { return v.Kill }).(pulumi.IntPtrOutput)
}

type VirtualMachinePowerTimeoutsPtrOutput struct{ *pulumi.OutputState }

func (VirtualMachinePowerTimeoutsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualMachinePowerTimeouts)(nil)).Elem()
}

func (o VirtualMachinePowerTimeoutsPtrOutput) ToVirtualMachinePowerTimeoutsPtrOutput() VirtualMachinePowerTimeoutsPtrOutput {
	return o
}

func (o VirtualMachinePowerTimeoutsPtrOutput) ToVirtualMachinePowerTimeoutsPtrOutputWithContext(ctx context.Context) VirtualMachinePowerTimeoutsPtrOutput {
	return o
}

func (o VirtualMachinePowerTimeoutsPtrOutput) Elem() VirtualMachinePowerTimeoutsOutput {
	return o.ApplyT(func(v *VirtualMachinePowerTimeouts) VirtualMachinePowerTimeouts {
		if v != nil {
			return *v
		}
		var ret VirtualMachinePowerTimeouts
		return ret
	}).(VirtualMachinePowerTimeoutsOutput)
}

func (o VirtualMachinePowerTimeoutsPtrOutput) Kill() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *VirtualMachinePowerTimeouts) *int {
		if v == nil {
			return nil
		}
		return v.Kill
	}).(pulumi.IntPtrOutput)
}

type VirtualMachineTimeouts struct {
	Create     *int `pulumi:"create"`
	Delete     *int `pulumi:"delete"`
	Kill       *int `pulumi:"kill"`
	Networking *int `pulumi:"networking"`
	Read       *int `pulumi:"read"`
	Update     *int `pulumi:"update"`
}

// VirtualMachineTimeoutsInput is an input type that accepts VirtualMachineTimeoutsArgs and VirtualMachineTimeoutsOutput values.
// You can construct a concrete instance of `VirtualMachineTimeoutsInput` via:
//
//	VirtualMachineTimeoutsArgs{...}
type VirtualMachineTimeoutsInput interface {
	pulumi.Input

	ToVirtualMachineTimeoutsOutput() VirtualMachineTimeoutsOutput
	ToVirtualMachineTimeoutsOutputWithContext(context.Context) VirtualMachineTimeoutsOutput
}

type VirtualMachineTimeoutsArgs struct {
	Create     pulumi.IntPtrInput `pulumi:"create"`
	Delete     pulumi.IntPtrInput `pulumi:"delete"`
	Kill       pulumi.IntPtrInput `pulumi:"kill"`
	Networking pulumi.IntPtrInput `pulumi:"networking"`
	Read       pulumi.IntPtrInput `pulumi:"read"`
	Update     pulumi.IntPtrInput `pulumi:"update"`
}

func (VirtualMachineTimeoutsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualMachineTimeouts)(nil)).Elem()
}

func (i VirtualMachineTimeoutsArgs) ToVirtualMachineTimeoutsOutput() VirtualMachineTimeoutsOutput {
	return i.ToVirtualMachineTimeoutsOutputWithContext(context.Background())
}

func (i VirtualMachineTimeoutsArgs) ToVirtualMachineTimeoutsOutputWithContext(ctx context.Context) VirtualMachineTimeoutsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualMachineTimeoutsOutput)
}

func (i VirtualMachineTimeoutsArgs) ToVirtualMachineTimeoutsPtrOutput() VirtualMachineTimeoutsPtrOutput {
	return i.ToVirtualMachineTimeoutsPtrOutputWithContext(context.Background())
}

func (i VirtualMachineTimeoutsArgs) ToVirtualMachineTimeoutsPtrOutputWithContext(ctx context.Context) VirtualMachineTimeoutsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualMachineTimeoutsOutput).ToVirtualMachineTimeoutsPtrOutputWithContext(ctx)
}

// VirtualMachineTimeoutsPtrInput is an input type that accepts VirtualMachineTimeoutsArgs, VirtualMachineTimeoutsPtr and VirtualMachineTimeoutsPtrOutput values.
// You can construct a concrete instance of `VirtualMachineTimeoutsPtrInput` via:
//
//	        VirtualMachineTimeoutsArgs{...}
//
//	or:
//
//	        nil
type VirtualMachineTimeoutsPtrInput interface {
	pulumi.Input

	ToVirtualMachineTimeoutsPtrOutput() VirtualMachineTimeoutsPtrOutput
	ToVirtualMachineTimeoutsPtrOutputWithContext(context.Context) VirtualMachineTimeoutsPtrOutput
}

type virtualMachineTimeoutsPtrType VirtualMachineTimeoutsArgs

func VirtualMachineTimeoutsPtr(v *VirtualMachineTimeoutsArgs) VirtualMachineTimeoutsPtrInput {
	return (*virtualMachineTimeoutsPtrType)(v)
}

func (*virtualMachineTimeoutsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualMachineTimeouts)(nil)).Elem()
}

func (i *virtualMachineTimeoutsPtrType) ToVirtualMachineTimeoutsPtrOutput() VirtualMachineTimeoutsPtrOutput {
	return i.ToVirtualMachineTimeoutsPtrOutputWithContext(context.Background())
}

func (i *virtualMachineTimeoutsPtrType) ToVirtualMachineTimeoutsPtrOutputWithContext(ctx context.Context) VirtualMachineTimeoutsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualMachineTimeoutsPtrOutput)
}

type VirtualMachineTimeoutsOutput struct{ *pulumi.OutputState }

func (VirtualMachineTimeoutsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualMachineTimeouts)(nil)).Elem()
}

func (o VirtualMachineTimeoutsOutput) ToVirtualMachineTimeoutsOutput() VirtualMachineTimeoutsOutput {
	return o
}

func (o VirtualMachineTimeoutsOutput) ToVirtualMachineTimeoutsOutputWithContext(ctx context.Context) VirtualMachineTimeoutsOutput {
	return o
}

func (o VirtualMachineTimeoutsOutput) ToVirtualMachineTimeoutsPtrOutput() VirtualMachineTimeoutsPtrOutput {
	return o.ToVirtualMachineTimeoutsPtrOutputWithContext(context.Background())
}

func (o VirtualMachineTimeoutsOutput) ToVirtualMachineTimeoutsPtrOutputWithContext(ctx context.Context) VirtualMachineTimeoutsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v VirtualMachineTimeouts) *VirtualMachineTimeouts {
		return &v
	}).(VirtualMachineTimeoutsPtrOutput)
}

func (o VirtualMachineTimeoutsOutput) Create() pulumi.IntPtrOutput {
	return o.ApplyT(func(v VirtualMachineTimeouts) *int { return v.Create }).(pulumi.IntPtrOutput)
}

func (o VirtualMachineTimeoutsOutput) Delete() pulumi.IntPtrOutput {
	return o.ApplyT(func(v VirtualMachineTimeouts) *int { return v.Delete }).(pulumi.IntPtrOutput)
}

func (o VirtualMachineTimeoutsOutput) Kill() pulumi.IntPtrOutput {
	return o.ApplyT(func(v VirtualMachineTimeouts) *int { return v.Kill }).(pulumi.IntPtrOutput)
}

func (o VirtualMachineTimeoutsOutput) Networking() pulumi.IntPtrOutput {
	return o.ApplyT(func(v VirtualMachineTimeouts) *int { return v.Networking }).(pulumi.IntPtrOutput)
}

func (o VirtualMachineTimeoutsOutput) Read() pulumi.IntPtrOutput {
	return o.ApplyT(func(v VirtualMachineTimeouts) *int { return v.Read }).(pulumi.IntPtrOutput)
}

func (o VirtualMachineTimeoutsOutput) Update() pulumi.IntPtrOutput {
	return o.ApplyT(func(v VirtualMachineTimeouts) *int { return v.Update }).(pulumi.IntPtrOutput)
}

type VirtualMachineTimeoutsPtrOutput struct{ *pulumi.OutputState }

func (VirtualMachineTimeoutsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualMachineTimeouts)(nil)).Elem()
}

func (o VirtualMachineTimeoutsPtrOutput) ToVirtualMachineTimeoutsPtrOutput() VirtualMachineTimeoutsPtrOutput {
	return o
}

func (o VirtualMachineTimeoutsPtrOutput) ToVirtualMachineTimeoutsPtrOutputWithContext(ctx context.Context) VirtualMachineTimeoutsPtrOutput {
	return o
}

func (o VirtualMachineTimeoutsPtrOutput) Elem() VirtualMachineTimeoutsOutput {
	return o.ApplyT(func(v *VirtualMachineTimeouts) VirtualMachineTimeouts {
		if v != nil {
			return *v
		}
		var ret VirtualMachineTimeouts
		return ret
	}).(VirtualMachineTimeoutsOutput)
}

func (o VirtualMachineTimeoutsPtrOutput) Create() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *VirtualMachineTimeouts) *int {
		if v == nil {
			return nil
		}
		return v.Create
	}).(pulumi.IntPtrOutput)
}

func (o VirtualMachineTimeoutsPtrOutput) Delete() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *VirtualMachineTimeouts) *int {
		if v == nil {
			return nil
		}
		return v.Delete
	}).(pulumi.IntPtrOutput)
}

func (o VirtualMachineTimeoutsPtrOutput) Kill() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *VirtualMachineTimeouts) *int {
		if v == nil {
			return nil
		}
		return v.Kill
	}).(pulumi.IntPtrOutput)
}

func (o VirtualMachineTimeoutsPtrOutput) Networking() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *VirtualMachineTimeouts) *int {
		if v == nil {
			return nil
		}
		return v.Networking
	}).(pulumi.IntPtrOutput)
}

func (o VirtualMachineTimeoutsPtrOutput) Read() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *VirtualMachineTimeouts) *int {
		if v == nil {
			return nil
		}
		return v.Read
	}).(pulumi.IntPtrOutput)
}

func (o VirtualMachineTimeoutsPtrOutput) Update() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *VirtualMachineTimeouts) *int {
		if v == nil {
			return nil
		}
		return v.Update
	}).(pulumi.IntPtrOutput)
}

type VmDistribution struct {
	Hash string `pulumi:"hash"`
	Name string `pulumi:"name"`
	Os   string `pulumi:"os"`
	Url  string `pulumi:"url"`
}

type VmDistributionOutput struct{ *pulumi.OutputState }

func (VmDistributionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VmDistribution)(nil)).Elem()
}

func (o VmDistributionOutput) ToVmDistributionOutput() VmDistributionOutput {
	return o
}

func (o VmDistributionOutput) ToVmDistributionOutputWithContext(ctx context.Context) VmDistributionOutput {
	return o
}

func (o VmDistributionOutput) Hash() pulumi.StringOutput {
	return o.ApplyT(func(v VmDistribution) string { return v.Hash }).(pulumi.StringOutput)
}

func (o VmDistributionOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v VmDistribution) string { return v.Name }).(pulumi.StringOutput)
}

func (o VmDistributionOutput) Os() pulumi.StringOutput {
	return o.ApplyT(func(v VmDistribution) string { return v.Os }).(pulumi.StringOutput)
}

func (o VmDistributionOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v VmDistribution) string { return v.Url }).(pulumi.StringOutput)
}

type VmDistributionArrayOutput struct{ *pulumi.OutputState }

func (VmDistributionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]VmDistribution)(nil)).Elem()
}

func (o VmDistributionArrayOutput) ToVmDistributionArrayOutput() VmDistributionArrayOutput {
	return o
}

func (o VmDistributionArrayOutput) ToVmDistributionArrayOutputWithContext(ctx context.Context) VmDistributionArrayOutput {
	return o
}

func (o VmDistributionArrayOutput) Index(i pulumi.IntInput) VmDistributionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) VmDistribution {
		return vs[0].([]VmDistribution)[vs[1].(int)]
	}).(VmDistributionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PollingSpecInput)(nil)).Elem(), PollingSpecArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*PollingSpecPtrInput)(nil)).Elem(), PollingSpecArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*RemoteFileAuthenticationInput)(nil)).Elem(), RemoteFileAuthenticationArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*RemoteFileAuthenticationPtrInput)(nil)).Elem(), RemoteFileAuthenticationArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*RemoteFileBasicAuthInput)(nil)).Elem(), RemoteFileBasicAuthArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*RemoteFileBasicAuthPtrInput)(nil)).Elem(), RemoteFileBasicAuthArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*RemoteFileExtractInput)(nil)).Elem(), RemoteFileExtractArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*RemoteFileExtractPtrInput)(nil)).Elem(), RemoteFileExtractArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*RemoteFilePollingInput)(nil)).Elem(), RemoteFilePollingArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*RemoteFilePollingPtrInput)(nil)).Elem(), RemoteFilePollingArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualDiskPollingInput)(nil)).Elem(), VirtualDiskPollingArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualDiskPollingPtrInput)(nil)).Elem(), VirtualDiskPollingArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualMachinePowerTimeoutsInput)(nil)).Elem(), VirtualMachinePowerTimeoutsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualMachinePowerTimeoutsPtrInput)(nil)).Elem(), VirtualMachinePowerTimeoutsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualMachineTimeoutsInput)(nil)).Elem(), VirtualMachineTimeoutsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualMachineTimeoutsPtrInput)(nil)).Elem(), VirtualMachineTimeoutsArgs{})
	pulumi.RegisterOutputType(DhcpLeaseInfoOutput{})
	pulumi.RegisterOutputType(DhcpLeaseInfoArrayOutput{})
	pulumi.RegisterOutputType(LanHostOutput{})
	pulumi.RegisterOutputType(LanHostPtrOutput{})
	pulumi.RegisterOutputType(LanHostL2IdentOutput{})
	pulumi.RegisterOutputType(LanHostL2IdentPtrOutput{})
	pulumi.RegisterOutputType(LanHostL3ConnectivityOutput{})
	pulumi.RegisterOutputType(LanHostL3ConnectivityArrayOutput{})
	pulumi.RegisterOutputType(LanHostNameOutput{})
	pulumi.RegisterOutputType(LanHostNameArrayOutput{})
	pulumi.RegisterOutputType(LanHostNetworkControlOutput{})
	pulumi.RegisterOutputType(LanHostNetworkControlPtrOutput{})
	pulumi.RegisterOutputType(LanInterfaceHostRefOutput{})
	pulumi.RegisterOutputType(LanInterfaceHostRefArrayOutput{})
	pulumi.RegisterOutputType(LanInterfaceInfoOutput{})
	pulumi.RegisterOutputType(LanInterfaceInfoArrayOutput{})
	pulumi.RegisterOutputType(NetworkingBindOutput{})
	pulumi.RegisterOutputType(NetworkingBindArrayOutput{})
	pulumi.RegisterOutputType(PollingSpecOutput{})
	pulumi.RegisterOutputType(PollingSpecPtrOutput{})
	pulumi.RegisterOutputType(RemoteFileAuthenticationOutput{})
	pulumi.RegisterOutputType(RemoteFileAuthenticationPtrOutput{})
	pulumi.RegisterOutputType(RemoteFileBasicAuthOutput{})
	pulumi.RegisterOutputType(RemoteFileBasicAuthPtrOutput{})
	pulumi.RegisterOutputType(RemoteFileExtractOutput{})
	pulumi.RegisterOutputType(RemoteFileExtractPtrOutput{})
	pulumi.RegisterOutputType(RemoteFilePollingOutput{})
	pulumi.RegisterOutputType(RemoteFilePollingPtrOutput{})
	pulumi.RegisterOutputType(VirtualDiskPollingOutput{})
	pulumi.RegisterOutputType(VirtualDiskPollingPtrOutput{})
	pulumi.RegisterOutputType(VirtualMachinePowerTimeoutsOutput{})
	pulumi.RegisterOutputType(VirtualMachinePowerTimeoutsPtrOutput{})
	pulumi.RegisterOutputType(VirtualMachineTimeoutsOutput{})
	pulumi.RegisterOutputType(VirtualMachineTimeoutsPtrOutput{})
	pulumi.RegisterOutputType(VmDistributionOutput{})
	pulumi.RegisterOutputType(VmDistributionArrayOutput{})
}
