// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package fw

import (
	"context"
	"reflect"

	"errors"
	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox"
	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type PortForwarding struct {
	pulumi.CustomResourceState

	// Optional comment for the rule.
	Comment pulumi.StringPtrOutput `pulumi:"comment"`
	// Whether the forwarding is enabled.
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// LAN host information for the target.
	Host freebox.LanHostPtrOutput `pulumi:"host"`
	// Hostname reported by the Freebox for this rule.
	Hostname pulumi.StringOutput `pulumi:"hostname"`
	// Protocol: tcp or udp.
	IpProtocol pulumi.StringOutput `pulumi:"ipProtocol"`
	// End of the WAN port range (defaults to portRangeStart).
	PortRangeEnd pulumi.IntPtrOutput `pulumi:"portRangeEnd"`
	// Start of the WAN port range (inclusive).
	PortRangeStart pulumi.IntOutput `pulumi:"portRangeStart"`
	// Freebox API rule ID.
	RuleId pulumi.IntOutput `pulumi:"ruleId"`
	// Source IP filter (0.0.0.0 = any).
	SourceIp pulumi.StringPtrOutput `pulumi:"sourceIp"`
	// Local IP of the port forwarding target.
	TargetIp pulumi.StringOutput `pulumi:"targetIp"`
	// Target LAN port (defaults to portRangeStart when range is a single port).
	TargetPort pulumi.IntPtrOutput `pulumi:"targetPort"`
}

// NewPortForwarding registers a new resource with the given unique name, arguments, and options.
func NewPortForwarding(ctx *pulumi.Context,
	name string, args *PortForwardingArgs, opts ...pulumi.ResourceOption) (*PortForwarding, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Enabled == nil {
		return nil, errors.New("invalid value for required argument 'Enabled'")
	}
	if args.IpProtocol == nil {
		return nil, errors.New("invalid value for required argument 'IpProtocol'")
	}
	if args.PortRangeStart == nil {
		return nil, errors.New("invalid value for required argument 'PortRangeStart'")
	}
	if args.TargetIp == nil {
		return nil, errors.New("invalid value for required argument 'TargetIp'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource PortForwarding
	err := ctx.RegisterResource("freebox:fw:PortForwarding", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPortForwarding gets an existing PortForwarding resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPortForwarding(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PortForwardingState, opts ...pulumi.ResourceOption) (*PortForwarding, error) {
	var resource PortForwarding
	err := ctx.ReadResource("freebox:fw:PortForwarding", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PortForwarding resources.
type portForwardingState struct {
}

type PortForwardingState struct {
}

func (PortForwardingState) ElementType() reflect.Type {
	return reflect.TypeOf((*portForwardingState)(nil)).Elem()
}

type portForwardingArgs struct {
	// Optional comment for the rule.
	Comment *string `pulumi:"comment"`
	// Whether the forwarding is enabled.
	Enabled bool `pulumi:"enabled"`
	// Protocol: tcp or udp.
	IpProtocol string `pulumi:"ipProtocol"`
	// End of the WAN port range (defaults to portRangeStart).
	PortRangeEnd *int `pulumi:"portRangeEnd"`
	// Start of the WAN port range (inclusive).
	PortRangeStart int `pulumi:"portRangeStart"`
	// Source IP filter (0.0.0.0 = any).
	SourceIp *string `pulumi:"sourceIp"`
	// Local IP of the port forwarding target.
	TargetIp string `pulumi:"targetIp"`
	// Target LAN port (defaults to portRangeStart when range is a single port).
	TargetPort *int `pulumi:"targetPort"`
}

// The set of arguments for constructing a PortForwarding resource.
type PortForwardingArgs struct {
	// Optional comment for the rule.
	Comment pulumi.StringPtrInput
	// Whether the forwarding is enabled.
	Enabled pulumi.BoolInput
	// Protocol: tcp or udp.
	IpProtocol pulumi.StringInput
	// End of the WAN port range (defaults to portRangeStart).
	PortRangeEnd pulumi.IntPtrInput
	// Start of the WAN port range (inclusive).
	PortRangeStart pulumi.IntInput
	// Source IP filter (0.0.0.0 = any).
	SourceIp pulumi.StringPtrInput
	// Local IP of the port forwarding target.
	TargetIp pulumi.StringInput
	// Target LAN port (defaults to portRangeStart when range is a single port).
	TargetPort pulumi.IntPtrInput
}

func (PortForwardingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*portForwardingArgs)(nil)).Elem()
}

type PortForwardingInput interface {
	pulumi.Input

	ToPortForwardingOutput() PortForwardingOutput
	ToPortForwardingOutputWithContext(ctx context.Context) PortForwardingOutput
}

func (*PortForwarding) ElementType() reflect.Type {
	return reflect.TypeOf((**PortForwarding)(nil)).Elem()
}

func (i *PortForwarding) ToPortForwardingOutput() PortForwardingOutput {
	return i.ToPortForwardingOutputWithContext(context.Background())
}

func (i *PortForwarding) ToPortForwardingOutputWithContext(ctx context.Context) PortForwardingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PortForwardingOutput)
}

// PortForwardingArrayInput is an input type that accepts PortForwardingArray and PortForwardingArrayOutput values.
// You can construct a concrete instance of `PortForwardingArrayInput` via:
//
//	PortForwardingArray{ PortForwardingArgs{...} }
type PortForwardingArrayInput interface {
	pulumi.Input

	ToPortForwardingArrayOutput() PortForwardingArrayOutput
	ToPortForwardingArrayOutputWithContext(context.Context) PortForwardingArrayOutput
}

type PortForwardingArray []PortForwardingInput

func (PortForwardingArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PortForwarding)(nil)).Elem()
}

func (i PortForwardingArray) ToPortForwardingArrayOutput() PortForwardingArrayOutput {
	return i.ToPortForwardingArrayOutputWithContext(context.Background())
}

func (i PortForwardingArray) ToPortForwardingArrayOutputWithContext(ctx context.Context) PortForwardingArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PortForwardingArrayOutput)
}

// PortForwardingMapInput is an input type that accepts PortForwardingMap and PortForwardingMapOutput values.
// You can construct a concrete instance of `PortForwardingMapInput` via:
//
//	PortForwardingMap{ "key": PortForwardingArgs{...} }
type PortForwardingMapInput interface {
	pulumi.Input

	ToPortForwardingMapOutput() PortForwardingMapOutput
	ToPortForwardingMapOutputWithContext(context.Context) PortForwardingMapOutput
}

type PortForwardingMap map[string]PortForwardingInput

func (PortForwardingMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PortForwarding)(nil)).Elem()
}

func (i PortForwardingMap) ToPortForwardingMapOutput() PortForwardingMapOutput {
	return i.ToPortForwardingMapOutputWithContext(context.Background())
}

func (i PortForwardingMap) ToPortForwardingMapOutputWithContext(ctx context.Context) PortForwardingMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PortForwardingMapOutput)
}

type PortForwardingOutput struct{ *pulumi.OutputState }

func (PortForwardingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PortForwarding)(nil)).Elem()
}

func (o PortForwardingOutput) ToPortForwardingOutput() PortForwardingOutput {
	return o
}

func (o PortForwardingOutput) ToPortForwardingOutputWithContext(ctx context.Context) PortForwardingOutput {
	return o
}

// Optional comment for the rule.
func (o PortForwardingOutput) Comment() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PortForwarding) pulumi.StringPtrOutput { return v.Comment }).(pulumi.StringPtrOutput)
}

// Whether the forwarding is enabled.
func (o PortForwardingOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *PortForwarding) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// LAN host information for the target.
func (o PortForwardingOutput) Host() freebox.LanHostPtrOutput {
	return o.ApplyT(func(v *PortForwarding) freebox.LanHostPtrOutput { return v.Host }).(freebox.LanHostPtrOutput)
}

// Hostname reported by the Freebox for this rule.
func (o PortForwardingOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v *PortForwarding) pulumi.StringOutput { return v.Hostname }).(pulumi.StringOutput)
}

// Protocol: tcp or udp.
func (o PortForwardingOutput) IpProtocol() pulumi.StringOutput {
	return o.ApplyT(func(v *PortForwarding) pulumi.StringOutput { return v.IpProtocol }).(pulumi.StringOutput)
}

// End of the WAN port range (defaults to portRangeStart).
func (o PortForwardingOutput) PortRangeEnd() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *PortForwarding) pulumi.IntPtrOutput { return v.PortRangeEnd }).(pulumi.IntPtrOutput)
}

// Start of the WAN port range (inclusive).
func (o PortForwardingOutput) PortRangeStart() pulumi.IntOutput {
	return o.ApplyT(func(v *PortForwarding) pulumi.IntOutput { return v.PortRangeStart }).(pulumi.IntOutput)
}

// Freebox API rule ID.
func (o PortForwardingOutput) RuleId() pulumi.IntOutput {
	return o.ApplyT(func(v *PortForwarding) pulumi.IntOutput { return v.RuleId }).(pulumi.IntOutput)
}

// Source IP filter (0.0.0.0 = any).
func (o PortForwardingOutput) SourceIp() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PortForwarding) pulumi.StringPtrOutput { return v.SourceIp }).(pulumi.StringPtrOutput)
}

// Local IP of the port forwarding target.
func (o PortForwardingOutput) TargetIp() pulumi.StringOutput {
	return o.ApplyT(func(v *PortForwarding) pulumi.StringOutput { return v.TargetIp }).(pulumi.StringOutput)
}

// Target LAN port (defaults to portRangeStart when range is a single port).
func (o PortForwardingOutput) TargetPort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *PortForwarding) pulumi.IntPtrOutput { return v.TargetPort }).(pulumi.IntPtrOutput)
}

type PortForwardingArrayOutput struct{ *pulumi.OutputState }

func (PortForwardingArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PortForwarding)(nil)).Elem()
}

func (o PortForwardingArrayOutput) ToPortForwardingArrayOutput() PortForwardingArrayOutput {
	return o
}

func (o PortForwardingArrayOutput) ToPortForwardingArrayOutputWithContext(ctx context.Context) PortForwardingArrayOutput {
	return o
}

func (o PortForwardingArrayOutput) Index(i pulumi.IntInput) PortForwardingOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *PortForwarding {
		return vs[0].([]*PortForwarding)[vs[1].(int)]
	}).(PortForwardingOutput)
}

type PortForwardingMapOutput struct{ *pulumi.OutputState }

func (PortForwardingMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PortForwarding)(nil)).Elem()
}

func (o PortForwardingMapOutput) ToPortForwardingMapOutput() PortForwardingMapOutput {
	return o
}

func (o PortForwardingMapOutput) ToPortForwardingMapOutputWithContext(ctx context.Context) PortForwardingMapOutput {
	return o
}

func (o PortForwardingMapOutput) MapIndex(k pulumi.StringInput) PortForwardingOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *PortForwarding {
		return vs[0].(map[string]*PortForwarding)[vs[1].(string)]
	}).(PortForwardingOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PortForwardingInput)(nil)).Elem(), &PortForwarding{})
	pulumi.RegisterInputType(reflect.TypeOf((*PortForwardingArrayInput)(nil)).Elem(), PortForwardingArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PortForwardingMapInput)(nil)).Elem(), PortForwardingMap{})
	pulumi.RegisterOutputType(PortForwardingOutput{})
	pulumi.RegisterOutputType(PortForwardingArrayOutput{})
	pulumi.RegisterOutputType(PortForwardingMapOutput{})
}
