// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package system

import (
	"context"
	"reflect"

	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetInfo(ctx *pulumi.Context, args *GetInfoArgs, opts ...pulumi.InvokeOption) (*GetInfoResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetInfoResult
	err := ctx.Invoke("freebox:system:getInfo", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetInfoArgs struct {
}

type GetInfoResult struct {
	BoardName        string `pulumi:"boardName"`
	BoxAuthenticated bool   `pulumi:"boxAuthenticated"`
	FanRpm           int    `pulumi:"fanRpm"`
	FirmwareVersion  string `pulumi:"firmwareVersion"`
	Mac              string `pulumi:"mac"`
	Serial           string `pulumi:"serial"`
	TempCpub         int    `pulumi:"tempCpub"`
	TempCpum         int    `pulumi:"tempCpum"`
	TempSw           int    `pulumi:"tempSw"`
	Uptime           string `pulumi:"uptime"`
	UptimeVal        int    `pulumi:"uptimeVal"`
	UserMainStorage  string `pulumi:"userMainStorage"`
}

func GetInfoOutput(ctx *pulumi.Context, args GetInfoOutputArgs, opts ...pulumi.InvokeOption) GetInfoResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetInfoResultOutput, error) {
			args := v.(GetInfoArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("freebox:system:getInfo", args, GetInfoResultOutput{}, options).(GetInfoResultOutput), nil
		}).(GetInfoResultOutput)
}

type GetInfoOutputArgs struct {
}

func (GetInfoOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInfoArgs)(nil)).Elem()
}

type GetInfoResultOutput struct{ *pulumi.OutputState }

func (GetInfoResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInfoResult)(nil)).Elem()
}

func (o GetInfoResultOutput) ToGetInfoResultOutput() GetInfoResultOutput {
	return o
}

func (o GetInfoResultOutput) ToGetInfoResultOutputWithContext(ctx context.Context) GetInfoResultOutput {
	return o
}

func (o GetInfoResultOutput) BoardName() pulumi.StringOutput {
	return o.ApplyT(func(v GetInfoResult) string { return v.BoardName }).(pulumi.StringOutput)
}

func (o GetInfoResultOutput) BoxAuthenticated() pulumi.BoolOutput {
	return o.ApplyT(func(v GetInfoResult) bool { return v.BoxAuthenticated }).(pulumi.BoolOutput)
}

func (o GetInfoResultOutput) FanRpm() pulumi.IntOutput {
	return o.ApplyT(func(v GetInfoResult) int { return v.FanRpm }).(pulumi.IntOutput)
}

func (o GetInfoResultOutput) FirmwareVersion() pulumi.StringOutput {
	return o.ApplyT(func(v GetInfoResult) string { return v.FirmwareVersion }).(pulumi.StringOutput)
}

func (o GetInfoResultOutput) Mac() pulumi.StringOutput {
	return o.ApplyT(func(v GetInfoResult) string { return v.Mac }).(pulumi.StringOutput)
}

func (o GetInfoResultOutput) Serial() pulumi.StringOutput {
	return o.ApplyT(func(v GetInfoResult) string { return v.Serial }).(pulumi.StringOutput)
}

func (o GetInfoResultOutput) TempCpub() pulumi.IntOutput {
	return o.ApplyT(func(v GetInfoResult) int { return v.TempCpub }).(pulumi.IntOutput)
}

func (o GetInfoResultOutput) TempCpum() pulumi.IntOutput {
	return o.ApplyT(func(v GetInfoResult) int { return v.TempCpum }).(pulumi.IntOutput)
}

func (o GetInfoResultOutput) TempSw() pulumi.IntOutput {
	return o.ApplyT(func(v GetInfoResult) int { return v.TempSw }).(pulumi.IntOutput)
}

func (o GetInfoResultOutput) Uptime() pulumi.StringOutput {
	return o.ApplyT(func(v GetInfoResult) string { return v.Uptime }).(pulumi.StringOutput)
}

func (o GetInfoResultOutput) UptimeVal() pulumi.IntOutput {
	return o.ApplyT(func(v GetInfoResult) int { return v.UptimeVal }).(pulumi.IntOutput)
}

func (o GetInfoResultOutput) UserMainStorage() pulumi.StringOutput {
	return o.ApplyT(func(v GetInfoResult) string { return v.UserMainStorage }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetInfoResultOutput{})
}
