// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package virtual

import (
	"context"
	"reflect"

	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox"
	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetDistributions(ctx *pulumi.Context, args *GetDistributionsArgs, opts ...pulumi.InvokeOption) (*GetDistributionsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDistributionsResult
	err := ctx.Invoke("freebox:virtual:getDistributions", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetDistributionsArgs struct {
}

type GetDistributionsResult struct {
	Distributions []freebox.VmDistribution `pulumi:"distributions"`
}

func GetDistributionsOutput(ctx *pulumi.Context, args GetDistributionsOutputArgs, opts ...pulumi.InvokeOption) GetDistributionsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetDistributionsResultOutput, error) {
			args := v.(GetDistributionsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("freebox:virtual:getDistributions", args, GetDistributionsResultOutput{}, options).(GetDistributionsResultOutput), nil
		}).(GetDistributionsResultOutput)
}

type GetDistributionsOutputArgs struct {
}

func (GetDistributionsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDistributionsArgs)(nil)).Elem()
}

type GetDistributionsResultOutput struct{ *pulumi.OutputState }

func (GetDistributionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDistributionsResult)(nil)).Elem()
}

func (o GetDistributionsResultOutput) ToGetDistributionsResultOutput() GetDistributionsResultOutput {
	return o
}

func (o GetDistributionsResultOutput) ToGetDistributionsResultOutputWithContext(ctx context.Context) GetDistributionsResultOutput {
	return o
}

func (o GetDistributionsResultOutput) Distributions() freebox.VmDistributionArrayOutput {
	return o.ApplyT(func(v GetDistributionsResult) []freebox.VmDistribution { return v.Distributions }).(freebox.VmDistributionArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDistributionsResultOutput{})
}
