// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package virtual

import (
	"context"
	"reflect"

	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetVirtualDisk(ctx *pulumi.Context, args *GetVirtualDiskArgs, opts ...pulumi.InvokeOption) (*GetVirtualDiskResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetVirtualDiskResult
	err := ctx.Invoke("freebox:virtual:getVirtualDisk", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetVirtualDiskArgs struct {
	Path string `pulumi:"path"`
}

type GetVirtualDiskResult struct {
	ActualSize  int    `pulumi:"actualSize"`
	Path        string `pulumi:"path"`
	Type        string `pulumi:"type"`
	VirtualSize int    `pulumi:"virtualSize"`
}

func GetVirtualDiskOutput(ctx *pulumi.Context, args GetVirtualDiskOutputArgs, opts ...pulumi.InvokeOption) GetVirtualDiskResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetVirtualDiskResultOutput, error) {
			args := v.(GetVirtualDiskArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("freebox:virtual:getVirtualDisk", args, GetVirtualDiskResultOutput{}, options).(GetVirtualDiskResultOutput), nil
		}).(GetVirtualDiskResultOutput)
}

type GetVirtualDiskOutputArgs struct {
	Path pulumi.StringInput `pulumi:"path"`
}

func (GetVirtualDiskOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVirtualDiskArgs)(nil)).Elem()
}

type GetVirtualDiskResultOutput struct{ *pulumi.OutputState }

func (GetVirtualDiskResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVirtualDiskResult)(nil)).Elem()
}

func (o GetVirtualDiskResultOutput) ToGetVirtualDiskResultOutput() GetVirtualDiskResultOutput {
	return o
}

func (o GetVirtualDiskResultOutput) ToGetVirtualDiskResultOutputWithContext(ctx context.Context) GetVirtualDiskResultOutput {
	return o
}

func (o GetVirtualDiskResultOutput) ActualSize() pulumi.IntOutput {
	return o.ApplyT(func(v GetVirtualDiskResult) int { return v.ActualSize }).(pulumi.IntOutput)
}

func (o GetVirtualDiskResultOutput) Path() pulumi.StringOutput {
	return o.ApplyT(func(v GetVirtualDiskResult) string { return v.Path }).(pulumi.StringOutput)
}

func (o GetVirtualDiskResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v GetVirtualDiskResult) string { return v.Type }).(pulumi.StringOutput)
}

func (o GetVirtualDiskResultOutput) VirtualSize() pulumi.IntOutput {
	return o.ApplyT(func(v GetVirtualDiskResult) int { return v.VirtualSize }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(GetVirtualDiskResultOutput{})
}
