// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package virtual

import (
	"context"
	"reflect"

	"errors"
	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox"
	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Machine struct {
	pulumi.CustomResourceState

	// USB ports to bind.
	BindUsbPorts pulumi.StringArrayOutput `pulumi:"bindUsbPorts"`
	// Path to CD/ISO image.
	CdPath pulumi.StringPtrOutput `pulumi:"cdPath"`
	// Cloud-init hostname.
	CloudinitHostname pulumi.StringPtrOutput `pulumi:"cloudinitHostname"`
	// Cloud-init user-data.
	CloudinitUserdata pulumi.StringPtrOutput `pulumi:"cloudinitUserdata"`
	// Path to the disk image.
	DiskPath pulumi.StringOutput `pulumi:"diskPath"`
	// Disk type: qcow2 or raw.
	DiskType pulumi.StringOutput `pulumi:"diskType"`
	// Enable cloud-init.
	EnableCloudinit pulumi.BoolPtrOutput `pulumi:"enableCloudinit"`
	// Enable VNC screen.
	EnableScreen pulumi.BoolPtrOutput `pulumi:"enableScreen"`
	// First IPv4 address of the VM on the LAN (when running).
	Ipv4 pulumi.StringPtrOutput `pulumi:"ipv4"`
	// MAC address of the VM.
	Mac pulumi.StringOutput `pulumi:"mac"`
	// Memory in MB.
	Memory pulumi.IntOutput `pulumi:"memory"`
	// Name of the VM.
	Name pulumi.StringOutput `pulumi:"name"`
	// Network binds (interface, IPv4, IPv6) for the VM.
	Networking freebox.NetworkingBindArrayOutput `pulumi:"networking"`
	// OS type (for icon).
	Os pulumi.StringPtrOutput `pulumi:"os"`
	// Current VM status (running/stopped).
	Status pulumi.StringOutput `pulumi:"status"`
	// Operation timeouts (create, update, read, delete, kill, networking).
	Timeouts freebox.VirtualMachineTimeoutsPtrOutput `pulumi:"timeouts"`
	// Number of vCPUs.
	Vcpus pulumi.IntOutput `pulumi:"vcpus"`
	// Freebox API VM ID.
	VmId pulumi.IntOutput `pulumi:"vmId"`
}

// NewMachine registers a new resource with the given unique name, arguments, and options.
func NewMachine(ctx *pulumi.Context,
	name string, args *MachineArgs, opts ...pulumi.ResourceOption) (*Machine, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DiskPath == nil {
		return nil, errors.New("invalid value for required argument 'DiskPath'")
	}
	if args.DiskType == nil {
		return nil, errors.New("invalid value for required argument 'DiskType'")
	}
	if args.Memory == nil {
		return nil, errors.New("invalid value for required argument 'Memory'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Vcpus == nil {
		return nil, errors.New("invalid value for required argument 'Vcpus'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Machine
	err := ctx.RegisterResource("freebox:virtual:Machine", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetMachine gets an existing Machine resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetMachine(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *MachineState, opts ...pulumi.ResourceOption) (*Machine, error) {
	var resource Machine
	err := ctx.ReadResource("freebox:virtual:Machine", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Machine resources.
type machineState struct {
}

type MachineState struct {
}

func (MachineState) ElementType() reflect.Type {
	return reflect.TypeOf((*machineState)(nil)).Elem()
}

type machineArgs struct {
	// USB ports to bind.
	BindUsbPorts []string `pulumi:"bindUsbPorts"`
	// Path to CD/ISO image.
	CdPath *string `pulumi:"cdPath"`
	// Cloud-init hostname.
	CloudinitHostname *string `pulumi:"cloudinitHostname"`
	// Cloud-init user-data.
	CloudinitUserdata *string `pulumi:"cloudinitUserdata"`
	// Path to the disk image.
	DiskPath string `pulumi:"diskPath"`
	// Disk type: qcow2 or raw.
	DiskType string `pulumi:"diskType"`
	// Enable cloud-init.
	EnableCloudinit *bool `pulumi:"enableCloudinit"`
	// Enable VNC screen.
	EnableScreen *bool `pulumi:"enableScreen"`
	// Memory in MB.
	Memory int `pulumi:"memory"`
	// Name of the VM.
	Name string `pulumi:"name"`
	// OS type (for icon).
	Os *string `pulumi:"os"`
	// Desired state: running or stopped. Default running.
	Status *string `pulumi:"status"`
	// Operation timeouts (create, update, read, delete, kill, networking).
	Timeouts *freebox.VirtualMachineTimeouts `pulumi:"timeouts"`
	// Number of vCPUs.
	Vcpus int `pulumi:"vcpus"`
}

// The set of arguments for constructing a Machine resource.
type MachineArgs struct {
	// USB ports to bind.
	BindUsbPorts pulumi.StringArrayInput
	// Path to CD/ISO image.
	CdPath pulumi.StringPtrInput
	// Cloud-init hostname.
	CloudinitHostname pulumi.StringPtrInput
	// Cloud-init user-data.
	CloudinitUserdata pulumi.StringPtrInput
	// Path to the disk image.
	DiskPath pulumi.StringInput
	// Disk type: qcow2 or raw.
	DiskType pulumi.StringInput
	// Enable cloud-init.
	EnableCloudinit pulumi.BoolPtrInput
	// Enable VNC screen.
	EnableScreen pulumi.BoolPtrInput
	// Memory in MB.
	Memory pulumi.IntInput
	// Name of the VM.
	Name pulumi.StringInput
	// OS type (for icon).
	Os pulumi.StringPtrInput
	// Desired state: running or stopped. Default running.
	Status pulumi.StringPtrInput
	// Operation timeouts (create, update, read, delete, kill, networking).
	Timeouts freebox.VirtualMachineTimeoutsPtrInput
	// Number of vCPUs.
	Vcpus pulumi.IntInput
}

func (MachineArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*machineArgs)(nil)).Elem()
}

type MachineInput interface {
	pulumi.Input

	ToMachineOutput() MachineOutput
	ToMachineOutputWithContext(ctx context.Context) MachineOutput
}

func (*Machine) ElementType() reflect.Type {
	return reflect.TypeOf((**Machine)(nil)).Elem()
}

func (i *Machine) ToMachineOutput() MachineOutput {
	return i.ToMachineOutputWithContext(context.Background())
}

func (i *Machine) ToMachineOutputWithContext(ctx context.Context) MachineOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MachineOutput)
}

// MachineArrayInput is an input type that accepts MachineArray and MachineArrayOutput values.
// You can construct a concrete instance of `MachineArrayInput` via:
//
//	MachineArray{ MachineArgs{...} }
type MachineArrayInput interface {
	pulumi.Input

	ToMachineArrayOutput() MachineArrayOutput
	ToMachineArrayOutputWithContext(context.Context) MachineArrayOutput
}

type MachineArray []MachineInput

func (MachineArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Machine)(nil)).Elem()
}

func (i MachineArray) ToMachineArrayOutput() MachineArrayOutput {
	return i.ToMachineArrayOutputWithContext(context.Background())
}

func (i MachineArray) ToMachineArrayOutputWithContext(ctx context.Context) MachineArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MachineArrayOutput)
}

// MachineMapInput is an input type that accepts MachineMap and MachineMapOutput values.
// You can construct a concrete instance of `MachineMapInput` via:
//
//	MachineMap{ "key": MachineArgs{...} }
type MachineMapInput interface {
	pulumi.Input

	ToMachineMapOutput() MachineMapOutput
	ToMachineMapOutputWithContext(context.Context) MachineMapOutput
}

type MachineMap map[string]MachineInput

func (MachineMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Machine)(nil)).Elem()
}

func (i MachineMap) ToMachineMapOutput() MachineMapOutput {
	return i.ToMachineMapOutputWithContext(context.Background())
}

func (i MachineMap) ToMachineMapOutputWithContext(ctx context.Context) MachineMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MachineMapOutput)
}

type MachineOutput struct{ *pulumi.OutputState }

func (MachineOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Machine)(nil)).Elem()
}

func (o MachineOutput) ToMachineOutput() MachineOutput {
	return o
}

func (o MachineOutput) ToMachineOutputWithContext(ctx context.Context) MachineOutput {
	return o
}

// USB ports to bind.
func (o MachineOutput) BindUsbPorts() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Machine) pulumi.StringArrayOutput { return v.BindUsbPorts }).(pulumi.StringArrayOutput)
}

// Path to CD/ISO image.
func (o MachineOutput) CdPath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Machine) pulumi.StringPtrOutput { return v.CdPath }).(pulumi.StringPtrOutput)
}

// Cloud-init hostname.
func (o MachineOutput) CloudinitHostname() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Machine) pulumi.StringPtrOutput { return v.CloudinitHostname }).(pulumi.StringPtrOutput)
}

// Cloud-init user-data.
func (o MachineOutput) CloudinitUserdata() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Machine) pulumi.StringPtrOutput { return v.CloudinitUserdata }).(pulumi.StringPtrOutput)
}

// Path to the disk image.
func (o MachineOutput) DiskPath() pulumi.StringOutput {
	return o.ApplyT(func(v *Machine) pulumi.StringOutput { return v.DiskPath }).(pulumi.StringOutput)
}

// Disk type: qcow2 or raw.
func (o MachineOutput) DiskType() pulumi.StringOutput {
	return o.ApplyT(func(v *Machine) pulumi.StringOutput { return v.DiskType }).(pulumi.StringOutput)
}

// Enable cloud-init.
func (o MachineOutput) EnableCloudinit() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Machine) pulumi.BoolPtrOutput { return v.EnableCloudinit }).(pulumi.BoolPtrOutput)
}

// Enable VNC screen.
func (o MachineOutput) EnableScreen() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Machine) pulumi.BoolPtrOutput { return v.EnableScreen }).(pulumi.BoolPtrOutput)
}

// First IPv4 address of the VM on the LAN (when running).
func (o MachineOutput) Ipv4() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Machine) pulumi.StringPtrOutput { return v.Ipv4 }).(pulumi.StringPtrOutput)
}

// MAC address of the VM.
func (o MachineOutput) Mac() pulumi.StringOutput {
	return o.ApplyT(func(v *Machine) pulumi.StringOutput { return v.Mac }).(pulumi.StringOutput)
}

// Memory in MB.
func (o MachineOutput) Memory() pulumi.IntOutput {
	return o.ApplyT(func(v *Machine) pulumi.IntOutput { return v.Memory }).(pulumi.IntOutput)
}

// Name of the VM.
func (o MachineOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Machine) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Network binds (interface, IPv4, IPv6) for the VM.
func (o MachineOutput) Networking() freebox.NetworkingBindArrayOutput {
	return o.ApplyT(func(v *Machine) freebox.NetworkingBindArrayOutput { return v.Networking }).(freebox.NetworkingBindArrayOutput)
}

// OS type (for icon).
func (o MachineOutput) Os() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Machine) pulumi.StringPtrOutput { return v.Os }).(pulumi.StringPtrOutput)
}

// Current VM status (running/stopped).
func (o MachineOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *Machine) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// Operation timeouts (create, update, read, delete, kill, networking).
func (o MachineOutput) Timeouts() freebox.VirtualMachineTimeoutsPtrOutput {
	return o.ApplyT(func(v *Machine) freebox.VirtualMachineTimeoutsPtrOutput { return v.Timeouts }).(freebox.VirtualMachineTimeoutsPtrOutput)
}

// Number of vCPUs.
func (o MachineOutput) Vcpus() pulumi.IntOutput {
	return o.ApplyT(func(v *Machine) pulumi.IntOutput { return v.Vcpus }).(pulumi.IntOutput)
}

// Freebox API VM ID.
func (o MachineOutput) VmId() pulumi.IntOutput {
	return o.ApplyT(func(v *Machine) pulumi.IntOutput { return v.VmId }).(pulumi.IntOutput)
}

type MachineArrayOutput struct{ *pulumi.OutputState }

func (MachineArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Machine)(nil)).Elem()
}

func (o MachineArrayOutput) ToMachineArrayOutput() MachineArrayOutput {
	return o
}

func (o MachineArrayOutput) ToMachineArrayOutputWithContext(ctx context.Context) MachineArrayOutput {
	return o
}

func (o MachineArrayOutput) Index(i pulumi.IntInput) MachineOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Machine {
		return vs[0].([]*Machine)[vs[1].(int)]
	}).(MachineOutput)
}

type MachineMapOutput struct{ *pulumi.OutputState }

func (MachineMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Machine)(nil)).Elem()
}

func (o MachineMapOutput) ToMachineMapOutput() MachineMapOutput {
	return o
}

func (o MachineMapOutput) ToMachineMapOutputWithContext(ctx context.Context) MachineMapOutput {
	return o
}

func (o MachineMapOutput) MapIndex(k pulumi.StringInput) MachineOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Machine {
		return vs[0].(map[string]*Machine)[vs[1].(string)]
	}).(MachineOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*MachineInput)(nil)).Elem(), &Machine{})
	pulumi.RegisterInputType(reflect.TypeOf((*MachineArrayInput)(nil)).Elem(), MachineArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*MachineMapInput)(nil)).Elem(), MachineMap{})
	pulumi.RegisterOutputType(MachineOutput{})
	pulumi.RegisterOutputType(MachineArrayOutput{})
	pulumi.RegisterOutputType(MachineMapOutput{})
}
