// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package virtual

import (
	"context"
	"reflect"

	"errors"
	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox"
	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type MachinePower struct {
	pulumi.CustomResourceState

	// Seconds to wait for graceful shutdown before force kill (default 30). Deprecated: use timeouts.kill.
	KillTimeout pulumi.IntPtrOutput `pulumi:"killTimeout"`
	// Desired power state: running or stopped.
	PowerState pulumi.StringOutput `pulumi:"powerState"`
	// Timeouts for power operations.
	Timeouts freebox.VirtualMachinePowerTimeoutsPtrOutput `pulumi:"timeouts"`
	// Identifier of the virtual machine.
	VmId pulumi.IntOutput `pulumi:"vmId"`
}

// NewMachinePower registers a new resource with the given unique name, arguments, and options.
func NewMachinePower(ctx *pulumi.Context,
	name string, args *MachinePowerArgs, opts ...pulumi.ResourceOption) (*MachinePower, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.PowerState == nil {
		return nil, errors.New("invalid value for required argument 'PowerState'")
	}
	if args.VmId == nil {
		return nil, errors.New("invalid value for required argument 'VmId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource MachinePower
	err := ctx.RegisterResource("freebox:virtual:MachinePower", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetMachinePower gets an existing MachinePower resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetMachinePower(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *MachinePowerState, opts ...pulumi.ResourceOption) (*MachinePower, error) {
	var resource MachinePower
	err := ctx.ReadResource("freebox:virtual:MachinePower", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering MachinePower resources.
type machinePowerState struct {
}

type MachinePowerState struct {
}

func (MachinePowerState) ElementType() reflect.Type {
	return reflect.TypeOf((*machinePowerState)(nil)).Elem()
}

type machinePowerArgs struct {
	// Seconds to wait for graceful shutdown before force kill (default 30). Deprecated: use timeouts.kill.
	KillTimeout *int `pulumi:"killTimeout"`
	// Desired power state: running or stopped.
	PowerState string `pulumi:"powerState"`
	// Timeouts for power operations.
	Timeouts *freebox.VirtualMachinePowerTimeouts `pulumi:"timeouts"`
	// Identifier of the virtual machine.
	VmId int `pulumi:"vmId"`
}

// The set of arguments for constructing a MachinePower resource.
type MachinePowerArgs struct {
	// Seconds to wait for graceful shutdown before force kill (default 30). Deprecated: use timeouts.kill.
	KillTimeout pulumi.IntPtrInput
	// Desired power state: running or stopped.
	PowerState pulumi.StringInput
	// Timeouts for power operations.
	Timeouts freebox.VirtualMachinePowerTimeoutsPtrInput
	// Identifier of the virtual machine.
	VmId pulumi.IntInput
}

func (MachinePowerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*machinePowerArgs)(nil)).Elem()
}

type MachinePowerInput interface {
	pulumi.Input

	ToMachinePowerOutput() MachinePowerOutput
	ToMachinePowerOutputWithContext(ctx context.Context) MachinePowerOutput
}

func (*MachinePower) ElementType() reflect.Type {
	return reflect.TypeOf((**MachinePower)(nil)).Elem()
}

func (i *MachinePower) ToMachinePowerOutput() MachinePowerOutput {
	return i.ToMachinePowerOutputWithContext(context.Background())
}

func (i *MachinePower) ToMachinePowerOutputWithContext(ctx context.Context) MachinePowerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MachinePowerOutput)
}

// MachinePowerArrayInput is an input type that accepts MachinePowerArray and MachinePowerArrayOutput values.
// You can construct a concrete instance of `MachinePowerArrayInput` via:
//
//	MachinePowerArray{ MachinePowerArgs{...} }
type MachinePowerArrayInput interface {
	pulumi.Input

	ToMachinePowerArrayOutput() MachinePowerArrayOutput
	ToMachinePowerArrayOutputWithContext(context.Context) MachinePowerArrayOutput
}

type MachinePowerArray []MachinePowerInput

func (MachinePowerArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*MachinePower)(nil)).Elem()
}

func (i MachinePowerArray) ToMachinePowerArrayOutput() MachinePowerArrayOutput {
	return i.ToMachinePowerArrayOutputWithContext(context.Background())
}

func (i MachinePowerArray) ToMachinePowerArrayOutputWithContext(ctx context.Context) MachinePowerArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MachinePowerArrayOutput)
}

// MachinePowerMapInput is an input type that accepts MachinePowerMap and MachinePowerMapOutput values.
// You can construct a concrete instance of `MachinePowerMapInput` via:
//
//	MachinePowerMap{ "key": MachinePowerArgs{...} }
type MachinePowerMapInput interface {
	pulumi.Input

	ToMachinePowerMapOutput() MachinePowerMapOutput
	ToMachinePowerMapOutputWithContext(context.Context) MachinePowerMapOutput
}

type MachinePowerMap map[string]MachinePowerInput

func (MachinePowerMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*MachinePower)(nil)).Elem()
}

func (i MachinePowerMap) ToMachinePowerMapOutput() MachinePowerMapOutput {
	return i.ToMachinePowerMapOutputWithContext(context.Background())
}

func (i MachinePowerMap) ToMachinePowerMapOutputWithContext(ctx context.Context) MachinePowerMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MachinePowerMapOutput)
}

type MachinePowerOutput struct{ *pulumi.OutputState }

func (MachinePowerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**MachinePower)(nil)).Elem()
}

func (o MachinePowerOutput) ToMachinePowerOutput() MachinePowerOutput {
	return o
}

func (o MachinePowerOutput) ToMachinePowerOutputWithContext(ctx context.Context) MachinePowerOutput {
	return o
}

// Seconds to wait for graceful shutdown before force kill (default 30). Deprecated: use timeouts.kill.
func (o MachinePowerOutput) KillTimeout() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *MachinePower) pulumi.IntPtrOutput { return v.KillTimeout }).(pulumi.IntPtrOutput)
}

// Desired power state: running or stopped.
func (o MachinePowerOutput) PowerState() pulumi.StringOutput {
	return o.ApplyT(func(v *MachinePower) pulumi.StringOutput { return v.PowerState }).(pulumi.StringOutput)
}

// Timeouts for power operations.
func (o MachinePowerOutput) Timeouts() freebox.VirtualMachinePowerTimeoutsPtrOutput {
	return o.ApplyT(func(v *MachinePower) freebox.VirtualMachinePowerTimeoutsPtrOutput { return v.Timeouts }).(freebox.VirtualMachinePowerTimeoutsPtrOutput)
}

// Identifier of the virtual machine.
func (o MachinePowerOutput) VmId() pulumi.IntOutput {
	return o.ApplyT(func(v *MachinePower) pulumi.IntOutput { return v.VmId }).(pulumi.IntOutput)
}

type MachinePowerArrayOutput struct{ *pulumi.OutputState }

func (MachinePowerArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*MachinePower)(nil)).Elem()
}

func (o MachinePowerArrayOutput) ToMachinePowerArrayOutput() MachinePowerArrayOutput {
	return o
}

func (o MachinePowerArrayOutput) ToMachinePowerArrayOutputWithContext(ctx context.Context) MachinePowerArrayOutput {
	return o
}

func (o MachinePowerArrayOutput) Index(i pulumi.IntInput) MachinePowerOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *MachinePower {
		return vs[0].([]*MachinePower)[vs[1].(int)]
	}).(MachinePowerOutput)
}

type MachinePowerMapOutput struct{ *pulumi.OutputState }

func (MachinePowerMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*MachinePower)(nil)).Elem()
}

func (o MachinePowerMapOutput) ToMachinePowerMapOutput() MachinePowerMapOutput {
	return o
}

func (o MachinePowerMapOutput) ToMachinePowerMapOutputWithContext(ctx context.Context) MachinePowerMapOutput {
	return o
}

func (o MachinePowerMapOutput) MapIndex(k pulumi.StringInput) MachinePowerOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *MachinePower {
		return vs[0].(map[string]*MachinePower)[vs[1].(string)]
	}).(MachinePowerOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*MachinePowerInput)(nil)).Elem(), &MachinePower{})
	pulumi.RegisterInputType(reflect.TypeOf((*MachinePowerArrayInput)(nil)).Elem(), MachinePowerArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*MachinePowerMapInput)(nil)).Elem(), MachinePowerMap{})
	pulumi.RegisterOutputType(MachinePowerOutput{})
	pulumi.RegisterOutputType(MachinePowerArrayOutput{})
	pulumi.RegisterOutputType(MachinePowerMapOutput{})
}
