// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package api

import (
	"context"
	"reflect"

	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func Version(ctx *pulumi.Context, args *VersionArgs, opts ...pulumi.InvokeOption) (*VersionResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv VersionResult
	err := ctx.Invoke("freebox:api:Version", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type VersionArgs struct {
}

type VersionResult struct {
	ApiBaseUrl     string `pulumi:"apiBaseUrl"`
	ApiDomain      string `pulumi:"apiDomain"`
	ApiVersion     string `pulumi:"apiVersion"`
	BoxModel       string `pulumi:"boxModel"`
	BoxModelName   string `pulumi:"boxModelName"`
	HttpsAvailable bool   `pulumi:"httpsAvailable"`
	HttpsPort      int    `pulumi:"httpsPort"`
	Uid            string `pulumi:"uid"`
}

func VersionOutput(ctx *pulumi.Context, args VersionOutputArgs, opts ...pulumi.InvokeOption) VersionResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (VersionResultOutput, error) {
			args := v.(VersionArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("freebox:api:Version", args, VersionResultOutput{}, options).(VersionResultOutput), nil
		}).(VersionResultOutput)
}

type VersionOutputArgs struct {
}

func (VersionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VersionArgs)(nil)).Elem()
}

type VersionResultOutput struct{ *pulumi.OutputState }

func (VersionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VersionResult)(nil)).Elem()
}

func (o VersionResultOutput) ToVersionResultOutput() VersionResultOutput {
	return o
}

func (o VersionResultOutput) ToVersionResultOutputWithContext(ctx context.Context) VersionResultOutput {
	return o
}

func (o VersionResultOutput) ApiBaseUrl() pulumi.StringOutput {
	return o.ApplyT(func(v VersionResult) string { return v.ApiBaseUrl }).(pulumi.StringOutput)
}

func (o VersionResultOutput) ApiDomain() pulumi.StringOutput {
	return o.ApplyT(func(v VersionResult) string { return v.ApiDomain }).(pulumi.StringOutput)
}

func (o VersionResultOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v VersionResult) string { return v.ApiVersion }).(pulumi.StringOutput)
}

func (o VersionResultOutput) BoxModel() pulumi.StringOutput {
	return o.ApplyT(func(v VersionResult) string { return v.BoxModel }).(pulumi.StringOutput)
}

func (o VersionResultOutput) BoxModelName() pulumi.StringOutput {
	return o.ApplyT(func(v VersionResult) string { return v.BoxModelName }).(pulumi.StringOutput)
}

func (o VersionResultOutput) HttpsAvailable() pulumi.BoolOutput {
	return o.ApplyT(func(v VersionResult) bool { return v.HttpsAvailable }).(pulumi.BoolOutput)
}

func (o VersionResultOutput) HttpsPort() pulumi.IntOutput {
	return o.ApplyT(func(v VersionResult) int { return v.HttpsPort }).(pulumi.IntOutput)
}

func (o VersionResultOutput) Uid() pulumi.StringOutput {
	return o.ApplyT(func(v VersionResult) string { return v.Uid }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(VersionResultOutput{})
}
