// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package downloads

import (
	"context"
	"reflect"

	"errors"
	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox"
	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type File struct {
	pulumi.CustomResourceState

	Authentication freebox.RemoteFileAuthenticationPtrOutput `pulumi:"authentication"`
	// Checksum of the file on disk.
	Checksum pulumi.StringOutput `pulumi:"checksum"`
	// Path on the Freebox where the file will be stored.
	DestinationPath pulumi.StringOutput                `pulumi:"destinationPath"`
	Extract         freebox.RemoteFileExtractPtrOutput `pulumi:"extract"`
	// Create parent directories if missing.
	Parents pulumi.BoolPtrOutput               `pulumi:"parents"`
	Polling freebox.RemoteFilePollingPtrOutput `pulumi:"polling"`
	// Size in bytes of the file on disk.
	SizeOnDisk pulumi.IntOutput `pulumi:"sizeOnDisk"`
	// Inline file content to upload.
	SourceContent pulumi.StringPtrOutput `pulumi:"sourceContent"`
	// Path to a local file to upload (relative to the Pulumi engine).
	SourceLocalFile pulumi.StringPtrOutput `pulumi:"sourceLocalFile"`
	// Path to an existing file on the Freebox to copy.
	SourceRemoteFile pulumi.StringPtrOutput `pulumi:"sourceRemoteFile"`
	// URL of the file to download.
	SourceUrl pulumi.StringPtrOutput `pulumi:"sourceUrl"`
}

// NewFile registers a new resource with the given unique name, arguments, and options.
func NewFile(ctx *pulumi.Context,
	name string, args *FileArgs, opts ...pulumi.ResourceOption) (*File, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DestinationPath == nil {
		return nil, errors.New("invalid value for required argument 'DestinationPath'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource File
	err := ctx.RegisterResource("freebox:downloads:File", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFile gets an existing File resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFile(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FileState, opts ...pulumi.ResourceOption) (*File, error) {
	var resource File
	err := ctx.ReadResource("freebox:downloads:File", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering File resources.
type fileState struct {
}

type FileState struct {
}

func (FileState) ElementType() reflect.Type {
	return reflect.TypeOf((*fileState)(nil)).Elem()
}

type fileArgs struct {
	Authentication *freebox.RemoteFileAuthentication `pulumi:"authentication"`
	// Expected checksum (method:value). Computed after create if omitted.
	Checksum *string `pulumi:"checksum"`
	// Path on the Freebox where the file will be stored.
	DestinationPath string                     `pulumi:"destinationPath"`
	Extract         *freebox.RemoteFileExtract `pulumi:"extract"`
	// Create parent directories if missing.
	Parents *bool                      `pulumi:"parents"`
	Polling *freebox.RemoteFilePolling `pulumi:"polling"`
	// Inline file content to upload.
	SourceContent *string `pulumi:"sourceContent"`
	// Path to a local file to upload (relative to the Pulumi engine).
	SourceLocalFile *string `pulumi:"sourceLocalFile"`
	// Path to an existing file on the Freebox to copy.
	SourceRemoteFile *string `pulumi:"sourceRemoteFile"`
	// URL of the file to download.
	SourceUrl *string `pulumi:"sourceUrl"`
}

// The set of arguments for constructing a File resource.
type FileArgs struct {
	Authentication freebox.RemoteFileAuthenticationPtrInput
	// Expected checksum (method:value). Computed after create if omitted.
	Checksum pulumi.StringPtrInput
	// Path on the Freebox where the file will be stored.
	DestinationPath pulumi.StringInput
	Extract         freebox.RemoteFileExtractPtrInput
	// Create parent directories if missing.
	Parents pulumi.BoolPtrInput
	Polling freebox.RemoteFilePollingPtrInput
	// Inline file content to upload.
	SourceContent pulumi.StringPtrInput
	// Path to a local file to upload (relative to the Pulumi engine).
	SourceLocalFile pulumi.StringPtrInput
	// Path to an existing file on the Freebox to copy.
	SourceRemoteFile pulumi.StringPtrInput
	// URL of the file to download.
	SourceUrl pulumi.StringPtrInput
}

func (FileArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*fileArgs)(nil)).Elem()
}

type FileInput interface {
	pulumi.Input

	ToFileOutput() FileOutput
	ToFileOutputWithContext(ctx context.Context) FileOutput
}

func (*File) ElementType() reflect.Type {
	return reflect.TypeOf((**File)(nil)).Elem()
}

func (i *File) ToFileOutput() FileOutput {
	return i.ToFileOutputWithContext(context.Background())
}

func (i *File) ToFileOutputWithContext(ctx context.Context) FileOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FileOutput)
}

// FileArrayInput is an input type that accepts FileArray and FileArrayOutput values.
// You can construct a concrete instance of `FileArrayInput` via:
//
//	FileArray{ FileArgs{...} }
type FileArrayInput interface {
	pulumi.Input

	ToFileArrayOutput() FileArrayOutput
	ToFileArrayOutputWithContext(context.Context) FileArrayOutput
}

type FileArray []FileInput

func (FileArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*File)(nil)).Elem()
}

func (i FileArray) ToFileArrayOutput() FileArrayOutput {
	return i.ToFileArrayOutputWithContext(context.Background())
}

func (i FileArray) ToFileArrayOutputWithContext(ctx context.Context) FileArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FileArrayOutput)
}

// FileMapInput is an input type that accepts FileMap and FileMapOutput values.
// You can construct a concrete instance of `FileMapInput` via:
//
//	FileMap{ "key": FileArgs{...} }
type FileMapInput interface {
	pulumi.Input

	ToFileMapOutput() FileMapOutput
	ToFileMapOutputWithContext(context.Context) FileMapOutput
}

type FileMap map[string]FileInput

func (FileMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*File)(nil)).Elem()
}

func (i FileMap) ToFileMapOutput() FileMapOutput {
	return i.ToFileMapOutputWithContext(context.Background())
}

func (i FileMap) ToFileMapOutputWithContext(ctx context.Context) FileMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FileMapOutput)
}

type FileOutput struct{ *pulumi.OutputState }

func (FileOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**File)(nil)).Elem()
}

func (o FileOutput) ToFileOutput() FileOutput {
	return o
}

func (o FileOutput) ToFileOutputWithContext(ctx context.Context) FileOutput {
	return o
}

func (o FileOutput) Authentication() freebox.RemoteFileAuthenticationPtrOutput {
	return o.ApplyT(func(v *File) freebox.RemoteFileAuthenticationPtrOutput { return v.Authentication }).(freebox.RemoteFileAuthenticationPtrOutput)
}

// Checksum of the file on disk.
func (o FileOutput) Checksum() pulumi.StringOutput {
	return o.ApplyT(func(v *File) pulumi.StringOutput { return v.Checksum }).(pulumi.StringOutput)
}

// Path on the Freebox where the file will be stored.
func (o FileOutput) DestinationPath() pulumi.StringOutput {
	return o.ApplyT(func(v *File) pulumi.StringOutput { return v.DestinationPath }).(pulumi.StringOutput)
}

func (o FileOutput) Extract() freebox.RemoteFileExtractPtrOutput {
	return o.ApplyT(func(v *File) freebox.RemoteFileExtractPtrOutput { return v.Extract }).(freebox.RemoteFileExtractPtrOutput)
}

// Create parent directories if missing.
func (o FileOutput) Parents() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *File) pulumi.BoolPtrOutput { return v.Parents }).(pulumi.BoolPtrOutput)
}

func (o FileOutput) Polling() freebox.RemoteFilePollingPtrOutput {
	return o.ApplyT(func(v *File) freebox.RemoteFilePollingPtrOutput { return v.Polling }).(freebox.RemoteFilePollingPtrOutput)
}

// Size in bytes of the file on disk.
func (o FileOutput) SizeOnDisk() pulumi.IntOutput {
	return o.ApplyT(func(v *File) pulumi.IntOutput { return v.SizeOnDisk }).(pulumi.IntOutput)
}

// Inline file content to upload.
func (o FileOutput) SourceContent() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *File) pulumi.StringPtrOutput { return v.SourceContent }).(pulumi.StringPtrOutput)
}

// Path to a local file to upload (relative to the Pulumi engine).
func (o FileOutput) SourceLocalFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *File) pulumi.StringPtrOutput { return v.SourceLocalFile }).(pulumi.StringPtrOutput)
}

// Path to an existing file on the Freebox to copy.
func (o FileOutput) SourceRemoteFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *File) pulumi.StringPtrOutput { return v.SourceRemoteFile }).(pulumi.StringPtrOutput)
}

// URL of the file to download.
func (o FileOutput) SourceUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *File) pulumi.StringPtrOutput { return v.SourceUrl }).(pulumi.StringPtrOutput)
}

type FileArrayOutput struct{ *pulumi.OutputState }

func (FileArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*File)(nil)).Elem()
}

func (o FileArrayOutput) ToFileArrayOutput() FileArrayOutput {
	return o
}

func (o FileArrayOutput) ToFileArrayOutputWithContext(ctx context.Context) FileArrayOutput {
	return o
}

func (o FileArrayOutput) Index(i pulumi.IntInput) FileOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *File {
		return vs[0].([]*File)[vs[1].(int)]
	}).(FileOutput)
}

type FileMapOutput struct{ *pulumi.OutputState }

func (FileMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*File)(nil)).Elem()
}

func (o FileMapOutput) ToFileMapOutput() FileMapOutput {
	return o
}

func (o FileMapOutput) ToFileMapOutputWithContext(ctx context.Context) FileMapOutput {
	return o
}

func (o FileMapOutput) MapIndex(k pulumi.StringInput) FileOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *File {
		return vs[0].(map[string]*File)[vs[1].(string)]
	}).(FileOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FileInput)(nil)).Elem(), &File{})
	pulumi.RegisterInputType(reflect.TypeOf((*FileArrayInput)(nil)).Elem(), FileArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*FileMapInput)(nil)).Elem(), FileMap{})
	pulumi.RegisterOutputType(FileOutput{})
	pulumi.RegisterOutputType(FileArrayOutput{})
	pulumi.RegisterOutputType(FileMapOutput{})
}
