// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dhcp

import (
	"context"
	"reflect"

	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox"
	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetLeases(ctx *pulumi.Context, args *GetLeasesArgs, opts ...pulumi.InvokeOption) (*GetLeasesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetLeasesResult
	err := ctx.Invoke("freebox:dhcp:getLeases", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetLeasesArgs struct {
}

type GetLeasesResult struct {
	Leases []freebox.DhcpLeaseInfo `pulumi:"leases"`
}

func GetLeasesOutput(ctx *pulumi.Context, args GetLeasesOutputArgs, opts ...pulumi.InvokeOption) GetLeasesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetLeasesResultOutput, error) {
			args := v.(GetLeasesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("freebox:dhcp:getLeases", args, GetLeasesResultOutput{}, options).(GetLeasesResultOutput), nil
		}).(GetLeasesResultOutput)
}

type GetLeasesOutputArgs struct {
}

func (GetLeasesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetLeasesArgs)(nil)).Elem()
}

type GetLeasesResultOutput struct{ *pulumi.OutputState }

func (GetLeasesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetLeasesResult)(nil)).Elem()
}

func (o GetLeasesResultOutput) ToGetLeasesResultOutput() GetLeasesResultOutput {
	return o
}

func (o GetLeasesResultOutput) ToGetLeasesResultOutputWithContext(ctx context.Context) GetLeasesResultOutput {
	return o
}

func (o GetLeasesResultOutput) Leases() freebox.DhcpLeaseInfoArrayOutput {
	return o.ApplyT(func(v GetLeasesResult) []freebox.DhcpLeaseInfo { return v.Leases }).(freebox.DhcpLeaseInfoArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetLeasesResultOutput{})
}
