// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dhcp

import (
	"context"
	"reflect"

	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetLease(ctx *pulumi.Context, args *GetLeaseArgs, opts ...pulumi.InvokeOption) (*GetLeaseResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetLeaseResult
	err := ctx.Invoke("freebox:dhcp:getLease", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetLeaseArgs struct {
	Mac string `pulumi:"mac"`
}

type GetLeaseResult struct {
	Comment  string `pulumi:"comment"`
	Hostname string `pulumi:"hostname"`
	Ip       string `pulumi:"ip"`
	LeaseId  string `pulumi:"leaseId"`
	Mac      string `pulumi:"mac"`
}

func GetLeaseOutput(ctx *pulumi.Context, args GetLeaseOutputArgs, opts ...pulumi.InvokeOption) GetLeaseResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetLeaseResultOutput, error) {
			args := v.(GetLeaseArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("freebox:dhcp:getLease", args, GetLeaseResultOutput{}, options).(GetLeaseResultOutput), nil
		}).(GetLeaseResultOutput)
}

type GetLeaseOutputArgs struct {
	Mac pulumi.StringInput `pulumi:"mac"`
}

func (GetLeaseOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetLeaseArgs)(nil)).Elem()
}

type GetLeaseResultOutput struct{ *pulumi.OutputState }

func (GetLeaseResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetLeaseResult)(nil)).Elem()
}

func (o GetLeaseResultOutput) ToGetLeaseResultOutput() GetLeaseResultOutput {
	return o
}

func (o GetLeaseResultOutput) ToGetLeaseResultOutputWithContext(ctx context.Context) GetLeaseResultOutput {
	return o
}

func (o GetLeaseResultOutput) Comment() pulumi.StringOutput {
	return o.ApplyT(func(v GetLeaseResult) string { return v.Comment }).(pulumi.StringOutput)
}

func (o GetLeaseResultOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v GetLeaseResult) string { return v.Hostname }).(pulumi.StringOutput)
}

func (o GetLeaseResultOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v GetLeaseResult) string { return v.Ip }).(pulumi.StringOutput)
}

func (o GetLeaseResultOutput) LeaseId() pulumi.StringOutput {
	return o.ApplyT(func(v GetLeaseResult) string { return v.LeaseId }).(pulumi.StringOutput)
}

func (o GetLeaseResultOutput) Mac() pulumi.StringOutput {
	return o.ApplyT(func(v GetLeaseResult) string { return v.Mac }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetLeaseResultOutput{})
}
