// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dhcp

import (
	"context"
	"reflect"

	"errors"
	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type StaticLease struct {
	pulumi.CustomResourceState

	// Optional comment for the lease.
	Comment pulumi.StringPtrOutput `pulumi:"comment"`
	// Optional hostname for the lease.
	Hostname pulumi.StringPtrOutput `pulumi:"hostname"`
	// IPv4 address to assign to the host.
	Ip pulumi.StringOutput `pulumi:"ip"`
	// MAC address of the host (resource identifier).
	Mac pulumi.StringOutput `pulumi:"mac"`
}

// NewStaticLease registers a new resource with the given unique name, arguments, and options.
func NewStaticLease(ctx *pulumi.Context,
	name string, args *StaticLeaseArgs, opts ...pulumi.ResourceOption) (*StaticLease, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Ip == nil {
		return nil, errors.New("invalid value for required argument 'Ip'")
	}
	if args.Mac == nil {
		return nil, errors.New("invalid value for required argument 'Mac'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource StaticLease
	err := ctx.RegisterResource("freebox:dhcp:StaticLease", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetStaticLease gets an existing StaticLease resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetStaticLease(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *StaticLeaseState, opts ...pulumi.ResourceOption) (*StaticLease, error) {
	var resource StaticLease
	err := ctx.ReadResource("freebox:dhcp:StaticLease", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering StaticLease resources.
type staticLeaseState struct {
}

type StaticLeaseState struct {
}

func (StaticLeaseState) ElementType() reflect.Type {
	return reflect.TypeOf((*staticLeaseState)(nil)).Elem()
}

type staticLeaseArgs struct {
	// Optional comment for the lease.
	Comment *string `pulumi:"comment"`
	// Optional hostname for the lease.
	Hostname *string `pulumi:"hostname"`
	// IPv4 address to assign to the host.
	Ip string `pulumi:"ip"`
	// MAC address of the host.
	Mac string `pulumi:"mac"`
}

// The set of arguments for constructing a StaticLease resource.
type StaticLeaseArgs struct {
	// Optional comment for the lease.
	Comment pulumi.StringPtrInput
	// Optional hostname for the lease.
	Hostname pulumi.StringPtrInput
	// IPv4 address to assign to the host.
	Ip pulumi.StringInput
	// MAC address of the host.
	Mac pulumi.StringInput
}

func (StaticLeaseArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*staticLeaseArgs)(nil)).Elem()
}

type StaticLeaseInput interface {
	pulumi.Input

	ToStaticLeaseOutput() StaticLeaseOutput
	ToStaticLeaseOutputWithContext(ctx context.Context) StaticLeaseOutput
}

func (*StaticLease) ElementType() reflect.Type {
	return reflect.TypeOf((**StaticLease)(nil)).Elem()
}

func (i *StaticLease) ToStaticLeaseOutput() StaticLeaseOutput {
	return i.ToStaticLeaseOutputWithContext(context.Background())
}

func (i *StaticLease) ToStaticLeaseOutputWithContext(ctx context.Context) StaticLeaseOutput {
	return pulumi.ToOutputWithContext(ctx, i).(StaticLeaseOutput)
}

// StaticLeaseArrayInput is an input type that accepts StaticLeaseArray and StaticLeaseArrayOutput values.
// You can construct a concrete instance of `StaticLeaseArrayInput` via:
//
//	StaticLeaseArray{ StaticLeaseArgs{...} }
type StaticLeaseArrayInput interface {
	pulumi.Input

	ToStaticLeaseArrayOutput() StaticLeaseArrayOutput
	ToStaticLeaseArrayOutputWithContext(context.Context) StaticLeaseArrayOutput
}

type StaticLeaseArray []StaticLeaseInput

func (StaticLeaseArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*StaticLease)(nil)).Elem()
}

func (i StaticLeaseArray) ToStaticLeaseArrayOutput() StaticLeaseArrayOutput {
	return i.ToStaticLeaseArrayOutputWithContext(context.Background())
}

func (i StaticLeaseArray) ToStaticLeaseArrayOutputWithContext(ctx context.Context) StaticLeaseArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(StaticLeaseArrayOutput)
}

// StaticLeaseMapInput is an input type that accepts StaticLeaseMap and StaticLeaseMapOutput values.
// You can construct a concrete instance of `StaticLeaseMapInput` via:
//
//	StaticLeaseMap{ "key": StaticLeaseArgs{...} }
type StaticLeaseMapInput interface {
	pulumi.Input

	ToStaticLeaseMapOutput() StaticLeaseMapOutput
	ToStaticLeaseMapOutputWithContext(context.Context) StaticLeaseMapOutput
}

type StaticLeaseMap map[string]StaticLeaseInput

func (StaticLeaseMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*StaticLease)(nil)).Elem()
}

func (i StaticLeaseMap) ToStaticLeaseMapOutput() StaticLeaseMapOutput {
	return i.ToStaticLeaseMapOutputWithContext(context.Background())
}

func (i StaticLeaseMap) ToStaticLeaseMapOutputWithContext(ctx context.Context) StaticLeaseMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(StaticLeaseMapOutput)
}

type StaticLeaseOutput struct{ *pulumi.OutputState }

func (StaticLeaseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**StaticLease)(nil)).Elem()
}

func (o StaticLeaseOutput) ToStaticLeaseOutput() StaticLeaseOutput {
	return o
}

func (o StaticLeaseOutput) ToStaticLeaseOutputWithContext(ctx context.Context) StaticLeaseOutput {
	return o
}

// Optional comment for the lease.
func (o StaticLeaseOutput) Comment() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *StaticLease) pulumi.StringPtrOutput { return v.Comment }).(pulumi.StringPtrOutput)
}

// Optional hostname for the lease.
func (o StaticLeaseOutput) Hostname() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *StaticLease) pulumi.StringPtrOutput { return v.Hostname }).(pulumi.StringPtrOutput)
}

// IPv4 address to assign to the host.
func (o StaticLeaseOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v *StaticLease) pulumi.StringOutput { return v.Ip }).(pulumi.StringOutput)
}

// MAC address of the host (resource identifier).
func (o StaticLeaseOutput) Mac() pulumi.StringOutput {
	return o.ApplyT(func(v *StaticLease) pulumi.StringOutput { return v.Mac }).(pulumi.StringOutput)
}

type StaticLeaseArrayOutput struct{ *pulumi.OutputState }

func (StaticLeaseArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*StaticLease)(nil)).Elem()
}

func (o StaticLeaseArrayOutput) ToStaticLeaseArrayOutput() StaticLeaseArrayOutput {
	return o
}

func (o StaticLeaseArrayOutput) ToStaticLeaseArrayOutputWithContext(ctx context.Context) StaticLeaseArrayOutput {
	return o
}

func (o StaticLeaseArrayOutput) Index(i pulumi.IntInput) StaticLeaseOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *StaticLease {
		return vs[0].([]*StaticLease)[vs[1].(int)]
	}).(StaticLeaseOutput)
}

type StaticLeaseMapOutput struct{ *pulumi.OutputState }

func (StaticLeaseMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*StaticLease)(nil)).Elem()
}

func (o StaticLeaseMapOutput) ToStaticLeaseMapOutput() StaticLeaseMapOutput {
	return o
}

func (o StaticLeaseMapOutput) ToStaticLeaseMapOutputWithContext(ctx context.Context) StaticLeaseMapOutput {
	return o
}

func (o StaticLeaseMapOutput) MapIndex(k pulumi.StringInput) StaticLeaseOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *StaticLease {
		return vs[0].(map[string]*StaticLease)[vs[1].(string)]
	}).(StaticLeaseOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*StaticLeaseInput)(nil)).Elem(), &StaticLease{})
	pulumi.RegisterInputType(reflect.TypeOf((*StaticLeaseArrayInput)(nil)).Elem(), StaticLeaseArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*StaticLeaseMapInput)(nil)).Elem(), StaticLeaseMap{})
	pulumi.RegisterOutputType(StaticLeaseOutput{})
	pulumi.RegisterOutputType(StaticLeaseArrayOutput{})
	pulumi.RegisterOutputType(StaticLeaseMapOutput{})
}
