// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/OlivierPaquien/pulumi-provider-freebox/sdk/go/freebox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The version of the API to use (default: latest).
func GetApiVersion(ctx *pulumi.Context) string {
	return config.Get(ctx, "freebox:apiVersion")
}

// The ID of the application for Freebox API authentication.
func GetAppId(ctx *pulumi.Context) string {
	return config.Get(ctx, "freebox:appId")
}

// The address of the Freebox (default: http://mafreebox.freebox.fr).
func GetEndpoint(ctx *pulumi.Context) string {
	return config.Get(ctx, "freebox:endpoint")
}

// The private token for Freebox API authentication.
func GetToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "freebox:token")
}
